export const contentData = [
  "PAGE A  /  COPYRIGHT REPRODUCTION POLICY",
  "Copyright Reproduction Policy",
  "Rules on copying, reproducing and redistributing our materials.",
  "1. PURPOSE OF THIS POLICY",
  "This Copyright Reproduction Policy (“Policy”) establishes the rules applicable to the reproduction, copying, duplication and creation of copies of qualifying copyrighted works owned or lawfully controlled by IB Cyber Security Private Limited (“Company”).",
  "The purpose of this Policy is to clarify when reproduction of Company-owned copyrighted materials may be permitted, when prior authorization may be required, and how statutory rights and third-party rights are preserved.",
  "This Policy shall be interpreted in accordance with applicable laws of India, including the Copyright Act, 1957, as amended from time to time.",
  "2. COPYRIGHT OWNER",
  "Copyright Owner: IB Cyber Security Private Limited | Public / Brand Name: IBCS | Private Limited Company.",
  "The Company reserves all copyright and related rights that it lawfully owns or controls in its qualifying original works and materials.",
  "3. MATERIALS COVERED BY THIS POLICY",
  "Subject to copyright subsisting in the material and ownership/control by the Company, this Policy applies to:",
  "• Website text, articles, publications, educational & cyber-awareness materials, reports, guides, PDFs, documents, & presentations• Images, photographs, graphics, illustrations, audio, video, animations, visual designs, logos, branding elements, icons, symbols, & watermarks• UI/UX creative expression, source code, software, digital assets, compilations, & arrangements",
  "4. MEANING OF REPRODUCTION",
  "“Reproduction” refers generally to making copies or reproductions of a qualifying copyrighted work in any form where restricted by copyright law.",
  "Includes: digital/physical copying, scanning, photocopying, downloading/retaining restricted copies, duplicating files, copying website text/source code/images/audiovisuals, and creating duplicate versions.",
  "PAGE B  /  COPYRIGHT REPRODUCTION POLICY",
  "5. GENERAL REPRODUCTION RULE",
  "Users must not reproduce Company-owned protected materials where reproduction is restricted by copyright law and no authorization, licence, or statutory exception permits it.",
  "Public availability on the Website does not, by itself, constitute a general licence to reproduce material.",
  "6. PERMITTED ACCESS AND VIEWING",
  "Users may access and personally view publicly available Website content through ordinary lawful Website use. Access does not transfer copyright ownership.",
  "7. PERSONAL USE",
  "A person may undertake reproduction where expressly permitted by applicable law, licence, or authorization. Statutory rights under Indian law remain unrestricted.",
  "8. WEBSITE CONTENT REPRODUCTION",
  "Company-owned articles, written content, educational materials, cyber-awareness guides, reports, and page content must not be substantially copied or reproduced for publication, redistribution, or commercial exploitation without authorization.",
  "PAGE A  /  COPYRIGHT REPRODUCTION POLICY",
  "9. IMAGE AND GRAPHIC REPRODUCTION",
  "Company-owned images, photographs, graphics, illustrations, icons, symbols, visual designs, and watermarks must not be reproduced without lawful authorization.",
  "10. AUDIO AND VIDEO REPRODUCTION",
  "Company-owned audio recordings, videos, animations, and audiovisual works must not be reproduced where restricted by law without valid permission.",
  "11. DOCUMENT REPRODUCTION",
  "PDFs, reports, guides, manuals, and presentations must not be reproduced or redistributed via photocopying, scanning, digital duplication, file sharing, document conversion, or platform uploads without authorization.",
  "12. SOURCE CODE REPRODUCTION",
  "Source code and software-related works must not be copied, reproduced, or redistributed where restricted. Third-party and open-source components remain subject to their respective licences.",
  "PAGE B  /  COPYRIGHT REPRODUCTION POLICY",
  "13. SCREENSHOTS AND SCREEN CAPTURES",
  "Screenshots of protected material must not be used for republication, commercial exploitation, or restricted purposes where authorization is required. Statutory exceptions under law remain unaffected.",
  "14. DOWNLOADS AND SAVED COPIES",
  "Where downloading or saving creates a restricted reproduction, the user must possess a valid licence or permission. Temporary technical caching copies are not prohibited.",
  "15. PRINTING AND PHOTOCOPYING",
  "Substantial printing or photocopying of protected materials constitutes reproduction and requires authorization unless a lawful exception applies.",
  "16. REPUBLICATION",
  "Reproducing Company material and publishing it elsewhere (other websites, apps, social media, video platforms, commercial/educational products) requires prior authorization.",
  "PAGE A  /  COPYRIGHT REPRODUCTION POLICY",
  "17. COMMERCIAL REPRODUCTION",
  "Commercial reproduction for paid products, services, advertising, marketing, commercial publications, apps, software, commercial websites, or resale requires prior written authorization.",
  "18. MASS OR SYSTEMATIC COPYING",
  "Systematic, automated, bulk or large-scale copying (automated content scraping, bulk downloads, database copying, automated republication) is prohibited without authorization.",
  "19. SOURCE CODE AND SOFTWARE COPYING",
  "Copying or incorporating Company-owned source code or software into another product requires authorization. Open-source rights under valid licences are preserved.",
  "20. MODIFIED OR ADAPTED COPIES",
  "Creating modified, translated, transformed, or adapted copies involves rights beyond simple reproduction and requires authorization unless permitted by law.",
  "PAGE B  /  COPYRIGHT REPRODUCTION POLICY",
  "21. ATTRIBUTION DOES NOT AUTHORIZE REPRODUCTION",
  "Providing attribution does not, by itself, authorize reproduction. Where permission is required, appropriate authorization must be obtained even if credit is provided.",
  "22. COPYRIGHT NOTICE PRESERVATION",
  "Copyright notices and ownership markings associated with reproduced materials should be preserved without unauthorized removal.",
  "23. PERMISSION FOR REPRODUCTION",
  "Written permission requests should be sent to: hr@ibcybersecurity.com detailing proposed material, purpose, format, audience, distribution method, commercial status, duration, and territory.",
  "24. WRITTEN AUTHORIZATION",
  "Where permission is granted, the Company specifies permitted material, format, purpose, duration, territory, platform, attribution, and restrictions. Authorization applies strictly to stated terms.",
  "PAGE A  /  COPYRIGHT REPRODUCTION POLICY",
  "25. NO IMPLIED PERMISSION FROM COMMUNICATION",
  "Email exchanges or discussions do not automatically constitute copyright permission unless evidenced through formal written authorization.",
  "26. LICENCE-BASED REPRODUCTION",
  "Reproduction permitted by a licence must remain strictly within licensed scope. Exceeding terms constitutes unauthorized use.",
  "27. THIRD-PARTY MATERIALS",
  "Open-source software, licensed images/fonts, third-party audio/video/graphics, and external services remain subject to their respective owners' rights.",
  "28. THIRD-PARTY AND OPEN-SOURCE LICENCES",
  "Governed by applicable third-party licence terms. Permitted open-source reproduction remains subject to third-party licence conditions.",
  "29. USER-GENERATED CONTENT",
  "Copyright and reproduction of user-submitted content are governed by applicable submission terms. The Company does not automatically claim ownership of user submissions.",
  "PAGE B  /  COPYRIGHT REPRODUCTION POLICY",
  "30. STATUTORY EXCEPTIONS AND LIMITATIONS",
  "Nothing restricts fair dealing, statutory exceptions, permitted acts, compulsory licences, or lawful defences under Indian copyright law.",
  "31. NO AUTOMATIC DETERMINATION OF INFRINGEMENT",
  "Reproduction does not automatically establish infringement in every case. Assessment depends on law, authorization, extent, statutory exceptions, and facts.",
  "32. COPYRIGHT INFRINGEMENT AND AVAILABLE REMEDIES",
  "Unauthorized infringement may trigger: cessation/removal requests, cease-and-desist communications, platform complaints, civil remedies, and criminal proceedings under Indian law.",
  "33. EVIDENCE AND RECORDS",
  "The Company maintains evidence logs (screenshots, URLs, source files, correspondence) in accordance with its Preservation Policy.",
  "34. NO WAIVER OF RIGHTS",
  "Failure to immediately object to an unauthorized reproduction does not constitute consent, waiver, or abandonment of legal rights.",
  "PAGE A  /  COPYRIGHT REPRODUCTION POLICY",
  "35. COPYRIGHT REGISTRATION",
  "Policy & Document ID (IBCS-COPYRIGHT-REPRODUCTION-POLICY-001) are internal control references, separate from government registration certificates.",
  "36. APPLICABLE INDIAN LAW",
  "Interpreted under Indian law, principally the Copyright Act, 1957 (Sections 13, 14, 17, 18, 19, 30, 30A, 51, 52, 55, 57). Statutory law prevails in case of conflict.",
  "37. GOVERNING LAW AND JURISDICTION",
  "Governed by Indian law. Jurisdiction resides in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "38. SEVERABILITY",
  "If any provision is determined invalid, remaining provisions continue to operate to the maximum extent legally permissible.",
  "39. RELATIONSHIP WITH OTHER COPYRIGHT POLICIES",
  "Read together with Attribution, Ownership, Permission, Licensing, Enforcement, and Preservation policies. Applicable law prevails in case of inconsistency.",
  "PAGE B  /  COPYRIGHT REPRODUCTION POLICY",
  "40. OFFICIAL COPYRIGHT INFORMATION",
  "IB Cyber Security Private Limited | Public / Brand Name: IBCS | Private Limited Company | Official Website: https://ibcybersecurity.com",
  "41. OFFICIAL CONTACT INFORMATION",
  "Permissions & Licensing: hr@ibcybersecurity.com | Infringement Reports: copyrightreport@ibcybersecurity.com | Legal Contact: legaldepartment@ibcybersecurity.com",
  "42. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited | Private Limited Company |  Phone:  | 8093424777",
  "43. DOCUMENT CONTROL",
  "Document Title: Copyright Reproduction Policy | Document ID: IBCS-COPYRIGHT-REPRODUCTION-POLICY-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.",
  "44. FINAL REPRODUCTION DECLARATION",
  "Qualifying original copyrighted materials lawfully owned or controlled by IB Cyber Security Private Limited are protected under applicable copyright law.",
  "No general licence to reproduce, copy, republish, distribute, modify, adapt or commercially exploit protected materials is granted merely because such materials are publicly accessible on https://ibcybersecurity.com.",
  "Where reproduction requires authorization, appropriate written permission should be obtained from the Company before undertaking the proposed use.",
  "Third-party materials remain subject to their respective owners' rights. Statutory exceptions under Indian law remain unaffected.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT REPRODUCTION POLICY"
];
