export const contentData = [
  "PAGE A  /  COPYRIGHT LICENSING POLICY",
  "Copyright Licensing Policy",
  "Terms and conditions for licensed use of our content.",
  "1. PURPOSE OF THIS COPYRIGHT LICENSING POLICY",
  "This Copyright Licensing Policy (“Policy”) establishes the principles, conditions and procedures governing the licensing of qualifying original copyrighted works owned or lawfully controlled by IB Cyber Security Private Limited (“Company”) and made available through or in connection with its official Website at https://ibcybersecurity.com (“Website”).",
  "The purpose of this Policy is to establish the circumstances in which the Company may grant a licence to use its protected original works and to define the scope, limitations, conditions, duration and other terms applicable to any such licence.",
  "This Policy shall be interpreted in accordance with the Copyright Act, 1957, as amended from time to time, other applicable laws of India, applicable licences, third-party rights and statutory exceptions and limitations.",
  "2. COPYRIGHT OWNER",
  "The copyright owner identified under this Policy is: IB Cyber Security Private Limited (Public / Brand Name: IBCS | Organization Type: Private Limited Company).",
  "The Company reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its qualifying original works and materials.",
  "3. MATERIALS THAT MAY BE LICENSED",
  "Subject to ownership or lawful control, a licence may be considered for qualifying original materials including:",
  "• Original website text, written content, articles, publications, educational & cyber-awareness materials• Original images, photographs, audio, videos, animations, graphics, illustrations, icons, & symbols• Original watermark designs, branding materials, UI/UX creative expression, visual designs, source code, software, PDFs, documents, presentations, digital assets, compilations, & arrangements",
  "A licence may be granted only to the extent that the Company lawfully owns or controls the relevant rights.",
  "PAGE B  /  COPYRIGHT LICENSING POLICY",
  "4. LICENSING PRINCIPLE",
  "The Company may, at its discretion and subject to applicable law, grant a licence permitting a person or organization to exercise specified rights in a qualifying copyrighted work.",
  "A licence grants only the rights expressly identified in the applicable written licence. No broader rights shall be inferred merely from website access, public availability, permission requests, previous use, downloading, or silence.",
  "5. WRITTEN LICENCE REQUIREMENT",
  "Where the Company grants a licence, the licence shall be documented in writing by the Company or its duly authorized agent.",
  "The written licence should clearly identify the rights being licensed, the scope of the licence and applicable terms. A permission request or informal communication does not constitute a licence.",
  "6. LICENSING REQUESTS",
  "Persons or organizations seeking a copyright licence should submit a written request to: hr@ibcybersecurity.com detailing the material and requested rights. Submission does not guarantee approval.",
  "7. INFORMATION REQUIRED FOR LICENSING REQUESTS",
  "A request should include: 1. Full name & organization, 2. Contact email & phone, 3. Work ID & URL, 4. Proposed use & purpose, 5. Commercial/non-commercial nature, 6. Platform, audience, duration & territory, 7. Distribution method & attribution details.",
  "PAGE A  /  COPYRIGHT LICENSING POLICY",
  "8. LICENSING REVIEW",
  "The Company evaluates requests individually, considering work nature, rights owned, proposed use, commercial status, portion requested, audience, distribution, duration, territory, modifications, sublicensing, third-party rights, and legal/commercial impact.",
  "9. DISCRETION TO GRANT OR REFUSE A LICENCE",
  "The Company may grant, grant with conditions/limitations, grant non-exclusive/exclusive terms, request further info, modify terms, or refuse a request. Submission creates no automatic entitlement.",
  "10. TYPES OF LICENCES",
  "Depending on circumstances, the Company may grant: non-exclusive, exclusive, limited-purpose, limited-duration, territory-specific, platform-specific, commercial, non-commercial, educational, or promotional licences.",
  "11. NON-EXCLUSIVE LICENCE",
  "Unless expressly stated in writing, a licence shall be treated as non-exclusive.",
  "A non-exclusive licence does not prevent the Company from continuing to use the work, licensing it to third parties, or exercising retained rights.",
  "PAGE B  /  COPYRIGHT LICENSING POLICY",
  "12. EXCLUSIVE LICENCE",
  "An exclusive licence arises only where expressly granted in a valid written instrument, identifying specific work, rights, exclusivity scope, duration, territory, and permitted uses.",
  "13. RIGHTS GRANTED UNDER A LICENCE",
  "A licence may grant specific rights (reproduction, publication, distribution, public communication, display, adaptation, translation, software use, commercial exploitation). Rights not expressly granted remain with the Company.",
  "14. SCOPE OF THE LICENCE",
  "A licence may be limited by work version, portion, purpose, platform, medium, territory, audience, duration, copies, or commercial activity. Use outside agreed scope requires extra authorization.",
  "15. DURATION OF LICENCE",
  "Granted for a specified period, project, campaign, publication, event, or product. Upon expiry, rights cease or revert according to licence terms and applicable law.",
  "PAGE A  /  COPYRIGHT LICENSING POLICY",
  "16. TERRITORIAL SCOPE",
  "May be limited to India, specific States/regions, specific countries, or worldwide (only if explicitly stated in writing).",
  "17. PLATFORM AND MEDIUM RESTRICTIONS",
  "May be limited to websites, mobile apps, social media, print, digital publications, educational platforms, video platforms, or internal systems.",
  "18. COMMERCIAL LICENSING",
  "The Company may grant commercial licences subject to terms determined in writing (purpose, duration, territory, distribution, fees, royalties, sublicensing, reporting).",
  "19. NON-COMMERCIAL LICENSING",
  "Non-commercial licences exclude sales, paid distribution, commercial ads, promotion, or sublicensing. Commercial exploitation requires separate authorization.",
  "PAGE B  /  COPYRIGHT LICENSING POLICY",
  "20. EDUCATIONAL LICENSING",
  "Specifies institution, course, material, copies, duration, and attribution. Does not restrict statutory educational exceptions under law.",
  "21. MODIFICATION AND ADAPTATION RIGHTS",
  "Does not automatically grant rights to modify, adapt, translate, or create derivative works. Permitted modifications must be expressly identified in writing.",
  "22. SOURCE CODE AND SOFTWARE LICENSING",
  "Specifies permitted use, installations, users, platforms, modifications, distribution, and security. Third-party components remain subject to their respective licences.",
  "23. IMAGES, AUDIO, VIDEO AND ANIMATION LICENSING",
  "Defines permitted use and restrictions for images, photos, graphics, audio, video, animations, and motion graphics owned or controlled by the Company.",
  "PAGE A  /  COPYRIGHT LICENSING POLICY",
  "24. DOCUMENT AND PUBLICATION LICENSING",
  "Defines reproduction and distribution scope for Company PDFs, reports, guides, manuals, educational assets, presentations, and publications.",
  "25. ATTRIBUTION",
  "Unless specified otherwise in writing, attribution should state:IB Cyber Security Private Limited | IBCS | Official Website: https://ibcybersecurity.com",
  "26. COPYRIGHT NOTICES AND WATERMARKS",
  "Licensees must preserve copyright notices (© 2026 IB Cyber Security Private Limited. All Rights Reserved.) and watermarks as required by written licence.",
  "27. SUBLICENSING",
  "Licensees may not sublicense, assign, or transfer licensed rights to another party unless the written licence expressly permits such action.",
  "PAGE B  /  COPYRIGHT LICENSING POLICY",
  "28. TRANSFER AND ASSIGNMENT",
  "A licence does not transfer copyright ownership. Rights cannot be assigned or transferred without written consent and formal legal instrument.",
  "29. ROYALTIES, FEES AND OTHER CONSIDERATION",
  "Consideration may include licence fees, royalties, one-time/recurring payments, or revenue sharing specified in the written agreement.",
  "30. RECORDS AND REPORTING",
  "Licensees may be required to maintain records of copies, sales, platforms, and users, and provide periodic compliance reports.",
  "31. LICENSEE RESPONSIBILITIES",
  "Licensees must operate strictly within licensed scope, comply with conditions, preserve attribution, respect third-party rights, and avoid false endorsement or ownership claims.",
  "PAGE A  /  COPYRIGHT LICENSING POLICY",
  "32. NO TRANSFER OF OWNERSHIP",
  "A licence grants permission to exercise specified rights; it does not transfer ownership of underlying copyright, which remains with IB Cyber Security Private Limited.",
  "33. NO IMPLIED RIGHTS",
  "Unstated rights remain reserved. Public availability, downloading, website access, past permissions, or correspondence do not expand a licence.",
  "34. THIRD-PARTY MATERIALS",
  "The Company does not grant licences over third-party materials (Google Fonts, open-source software, licensed media). Third-party permissions must be obtained separately.",
  "35. STATUTORY EXCEPTIONS AND LIMITATIONS",
  "Nothing in this Policy restricts statutory exceptions, fair dealing, or compulsory/statutory licensing independently available under Indian copyright law.",
  "PAGE B  /  COPYRIGHT LICENSING POLICY",
  "36. COMPULSORY AND STATUTORY LICENCES",
  "Nothing in this Policy overrides compulsory or statutory licensing mechanisms established under Indian copyright law.",
  "37. LICENCE BREACH",
  "Use outside licensed scope constitutes unauthorized use, contract breach, and potential copyright infringement, reserving all legal remedies.",
  "38. SUSPENSION OR TERMINATION",
  "Licences may be suspended or terminated for material breach, unauthorized sublicensing, fee default, scope violation, or false ownership claims.",
  "39. EFFECT OF TERMINATION",
  "Upon termination/expiry, licensees must cease use, remove materials, destroy copies, stop commercial exploitation, and confirm compliance.",
  "PAGE A  /  COPYRIGHT LICENSING POLICY",
  "40. INFRINGEMENT AFTER LICENCE EXPIRY OR TERMINATION",
  "Continued use of protected Company materials after licence expiry or termination constitutes unauthorized use and copyright infringement.",
  "41. LICENCE AMENDMENTS",
  "Material amendments must be documented in writing. Oral statements do not amend a written licence.",
  "42. LICENCE INTERPRETATION",
  "Interpreted according to written terms, Indian copyright law, and mandatory statutory provisions. Statutory law prevails over conflicting terms.",
  "43. COPYRIGHT REGISTRATION",
  "Document ID (IBCS-COPYRIGHT-LICENSING-POLICY-001) is an internal control reference, not a government registration certificate.",
  "PAGE B  /  COPYRIGHT LICENSING POLICY",
  "44. INFRINGEMENT AND ENFORCEMENT",
  "Unauthorized use outside valid licence or statutory exception constitutes infringement. The Company reserves all civil, criminal, and legal remedies under Indian law.",
  "45. COPYRIGHT INFRINGEMENT REPORTING",
  "Suspected infringement may be reported to: copyrightreport@ibcybersecurity.com with work ID, location URL, description, evidence, and reporter contact info.",
  "46. WEBSITE UNDER MAINTENANCE",
  "Website maintenance, redesign, or asset updates do not automatically alter, expand, or terminate existing written licences.",
  "47. POLICY INTERPRETATION",
  "Interpreted consistently with Indian copyright law. Mandatory statutory provisions prevail over conflicting Policy terms.",
  "PAGE A  /  COPYRIGHT LICENSING POLICY",
  "48. APPLICABLE INDIAN LAW",
  "Governed principally by the Copyright Act, 1957 (Sections 13, 14, 17, 18, 19, 30, 30A, 51, 52). Section 30 permits written licensing by copyright owners or authorized agents.",
  "49. GOVERNING LAW AND JURISDICTION",
  "Governed by Indian law. Jurisdiction resides in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "50. OFFICIAL LICENSING CONTACT",
  "Licensing & Permission Requests: hr@ibcybersecurity.comInfringement Reports: copyrightreport@ibcybersecurity.comLegal Contact: legaldepartment@ibcybersecurity.com",
  "51. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited | Public / Brand Name: IBCS | Private Limited Company",
  "Phone:  | 8093424777",
  "PAGE B  /  COPYRIGHT LICENSING POLICY",
  "52. DOCUMENT CONTROL",
  "Document Title: Copyright Licensing Policy | Document ID: IBCS-COPYRIGHT-LICENSING-POLICY-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.",
  "53. COPYRIGHT STATEMENT",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "IB Cyber Security Private Limited reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its qualifying original works and materials.",
  "54. FINAL LICENSING DECLARATION",
  "IB Cyber Security Private Limited may grant written copyright licences for qualifying original works that it lawfully owns or controls.",
  "A licence grants only specified written rights and does not transfer ownership. Unstated rights remain reserved.",
  "Third-party materials remain subject to their respective owners' rights. Statutory exceptions under Indian law remain unaffected.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT LICENSING POLICY"
];
