export const contentData = [
  "PAGE A  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "Copyright Content Protection Policy",
  "Measures to safeguard our digital content from theft, alteration and misuse.",
  "1. PURPOSE OF THIS POLICY",
  "This Copyright Content Protection Policy (“Policy”) establishes the framework of IB Cyber Security Private Limited (“Company”) for protecting qualifying copyrighted content and materials that are lawfully owned or controlled by the Company.",
  "The purpose of this Policy is to establish reasonable measures for identifying, protecting, monitoring, documenting and responding to unauthorized use of Company-owned copyrighted content.",
  "This Policy shall be interpreted in accordance with applicable laws of India, including the Copyright Act, 1957, as amended from time to time.",
  "2. COPYRIGHT OWNER",
  "Copyright Owner: IB Cyber Security Private Limited | Public / Brand Name: IBCS | Organization Type: Private Limited Company.",
  "The Company reserves all copyright and related rights that it lawfully owns or controls.",
  "3. SCOPE OF PROTECTED CONTENT",
  "Subject to copyright subsisting in the material and the Company lawfully owning or controlling the applicable rights, this Policy may apply to:",
  "• Website text, articles, publications, educational & cyber-awareness materials, reports, guides, PDFs, documents, & presentations• Images, photographs, graphics, illustrations, audio, video, animations, visual designs, branding materials, logos, icons, symbols, & watermarks• UI/UX creative expression, source code, software, digital assets, qualifying compilations, arrangements, & other literary/artistic/audiovisual/digital works",
  "PAGE B  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "4. LIMITATION OF PROTECTION",
  "Copyright protection applies only to material that is legally protectable and to the extent that the Company lawfully owns or controls the relevant rights.",
  "This Policy does not claim exclusive rights over: ideas, facts, methods, procedures, concepts, systems, principles, or other unprotectable subject matter.",
  "5. CONTENT OWNERSHIP",
  "The Company asserts and reserves the copyright and related rights that it lawfully owns or controls in its qualifying original content.",
  "Where ownership depends upon an agreement, assignment, licence, or employment arrangement, the applicable legal instrument and law shall govern.",
  "6. CONTENT IDENTIFICATION",
  "The Company may identify qualifying protected content through copyright notices, watermarks, branding, metadata, document identifiers, version information, publication records, internal logs, and technical identifiers.",
  "7. COPYRIGHT NOTICE",
  "The standard copyright notice used by the Company is: © 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "The absence of a copyright notice from a particular item does not, by itself, constitute abandonment or waiver of copyright where copyright otherwise subsists.",
  "PAGE A  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "8. CONTENT PROTECTION MEASURES",
  "The Company may use access controls, authentication, copyright notices, watermarks, technical restrictions, security controls, content-management controls, version control, source-code limits, monitoring, and record preservation.",
  "9. DIGITAL CONTENT PROTECTION",
  "Implements reasonable measures to reduce unauthorized copying, extraction, alteration, redistribution, or unauthorized use of website text, digital documents, source code, images, audio, video, graphics, and digital assets.",
  "10. SOURCE CODE PROTECTION",
  "Source code access is restricted to authorized personnel using repository access controls, authentication, permission management, version control, access logging, and backup systems.",
  "11. CONTENT ACCESS CONTROLS",
  "Determines public, internal, restricted, or confidential access based on business, security, copyright, licensing, legal, and operational requirements.",
  "PAGE B  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "12. WATERMARKS AND IDENTIFIERS",
  "Uses watermarks, logos, copyright notices, or other identifiers. Unauthorized removal, alteration, or concealment of such identifiers constitutes unauthorized conduct where prohibited by law.",
  "13. CONTENT MONITORING",
  "Periodically reviews websites, search results, social-media platforms, video platforms, online publications, digital repositories, and online marketplaces for unauthorized use.",
  "14. AUTOMATED MONITORING",
  "May use automated or semi-automated methods to identify potentially unauthorized copies. Systems assist detection but do not automatically establish infringement without human review.",
  "15. CONTENT MATCHING",
  "Compares suspected copies with original works using text, image, audio, video, source-code, metadata, and version comparison methods.",
  "PAGE A  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "16. NO AUTOMATIC DETERMINATION OF INFRINGEMENT",
  "A content match, similarity, screenshot, or detection alert does not automatically establish copyright infringement. Determination depends upon law, ownership, authorization, licence scope, statutory exceptions, fair dealing, and facts.",
  "17. IDENTIFICATION OF SUSPECTED UNAUTHORIZED USE",
  "Documents location, URL, account/platform details, observation date/time, screenshots, relevant copies, comparison with original works, and publication information.",
  "18. EVIDENCE PRESERVATION",
  "Preserves screenshots, URLs, copies, source files, version histories, publication records, metadata, correspondence, licence records, and technical info under its Evidence Preservation Policy.",
  "19. EVIDENCE INTEGRITY",
  "Takes reasonable measures to preserve digital evidence integrity: maintaining original copies, recording timestamps, preserving metadata, logging storage access, versioning, and using file hashes.",
  "PAGE B  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "20. THIRD-PARTY MATERIALS",
  "Open-source software, licensed images, licensed fonts, third-party audio/video/graphics, embedded content, and third-party services remain subject to their respective owners' rights.",
  "21. THIRD-PARTY LICENCES",
  "Protection measures do not override valid third-party or open-source licence rights. Permitted third-party uses remain governed by their applicable licence terms.",
  "22. USER-GENERATED CONTENT",
  "User-submitted content is governed by applicable terms/licences. The Company does not automatically claim copyright ownership over user-generated content.",
  "23. CONTENT SECURITY",
  "Implements access management, authentication, authorization, secure storage, backups, monitoring, logging, and security updates to safeguard digital content.",
  "PAGE A  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "24. BACKUP AND RECOVERY",
  "Maintains backups of important digital content for recovery, business continuity, evidence preservation, version restoration, security, and legal/compliance purposes.",
  "25. CONTENT MODIFICATION",
  "Unauthorized alteration, modification, adaptation, or transformation of protected Company content may constitute infringement unless permitted by applicable law.",
  "26. CONTENT REPUBLICATION",
  "Republication on external websites, social media, video platforms, documents, apps, or commercial materials requires prior authorization where restricted by copyright law.",
  "27. COMMERCIAL EXPLOITATION",
  "Commercial resale, paid publications, commercial advertising, marketing, paid training, commercial software, websites, or products require prior written authorization.",
  "PAGE B  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "28. ATTRIBUTION",
  "Attribution does not, by itself, create permission to reproduce or use content. Where authorization is required, credit does not replace formal authorization.",
  "29. REPRODUCTION",
  "Reproduction of qualifying Company-owned content is governed by the Copyright Reproduction Policy, which operates in synergy with this Policy.",
  "30. PERMISSION AND LICENSING",
  "Permission requests should be submitted to: hr@ibcybersecurity.com. Granted permissions may specify conditions, scope, duration, territory, and permitted uses.",
  "31. UNAUTHORIZED USE RESPONSE",
  "Steps may include: contacting publishers, requesting cessation/removal, requesting correction, issuing C&D communications, platform complaints, takedowns, civil suits, and criminal proceedings.",
  "PAGE A  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "32. COPYRIGHT INFRINGEMENT REPORTING",
  "Suspected infringement may be reported to: copyrightreport@ibcybersecurity.com including work ID, infringing URL, explanation, supporting evidence, and contact details.",
  "33. REVIEW OF REPORTS",
  "The Company reviews reports and supporting evidence, requesting additional info if needed. Receipt of a report does not automatically admit infringement.",
  "34. REMOVAL AND TAKEDOWN REQUESTS",
  "Requests removal or disabling of access through relevant websites, platforms, hosting providers, or search engines in accordance with applicable law and platform procedures.",
  "35. NO FALSE CLAIMS",
  "The Company does not knowingly make false claims of copyright ownership or infringement. Enforcement is based strictly on lawful rights and verified facts.",
  "PAGE B  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "36. LEGAL REMEDIES",
  "Pursues all civil, criminal, administrative, and platform-based remedies lawfully available under applicable law for established copyright infringement.",
  "37. STATUTORY EXCEPTIONS AND LIMITATIONS",
  "Nothing restricts fair dealing, statutory exceptions, permitted acts, compulsory licences, statutory licences, or lawful defences under Indian copyright law.",
  "38. NO WAIVER OF RIGHTS",
  "Failure to take immediate action against a particular use does not constitute consent, authorization, waiver, ownership transfer, or abandonment of rights.",
  "39. COPYRIGHT REGISTRATION",
  "Policy & Document ID (IBCS-COPYRIGHT-CONTENT-PROTECTION-POLICY-001) are internal document control references, separate from government registration certificates.",
  "PAGE A  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "40. RELATIONSHIP WITH OTHER COPYRIGHT POLICIES",
  "Read together with Notice, Disclaimer, Permission, Licensing, Attribution, Reproduction, Enforcement, and Preservation policies. Applicable law prevails in case of conflict.",
  "41. APPLICABLE INDIAN LAW",
  "Interpreted under Indian law, principally the Copyright Act, 1957 (Sections 13, 14, 17, 18, 19, 30, 30A, 51, 52, 55, 57). Mandatory legal provisions prevail.",
  "42. GOVERNING LAW AND JURISDICTION",
  "Governed by Indian law. Jurisdiction resides in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "43. SEVERABILITY",
  "If any provision is determined invalid, remaining provisions continue in effect to the maximum extent legally permissible under law.",
  "PAGE B  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "44. POLICY INTERPRETATION",
  "Interpreted consistently with applicable Indian law. Mandatory statutory provisions prevail over conflicting Policy terms.",
  "45. OFFICIAL COPYRIGHT INFORMATION",
  "Copyright Owner: IB Cyber Security Private Limited | Public / Brand Name: IBCS | Private Limited Company | Official Website: https://ibcybersecurity.com",
  "46. OFFICIAL CONTACT INFORMATION",
  "Permissions & Licensing: hr@ibcybersecurity.com | Infringement Reports: copyrightreport@ibcybersecurity.com | Legal Contact: legaldepartment@ibcybersecurity.com",
  "PAGE A  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "47. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited | Public / Brand Name: IBCS | Private Limited Company",
  "Official Website: https://ibcybersecurity.com | Email: hr@ibcybersecurity.com | Legal: legaldepartment@ibcybersecurity.com | Infringements: copyrightreport@ibcybersecurity.com | Phone:  | 8093424777",
  "48. DOCUMENT CONTROL",
  "Document Title: Copyright Content Protection Policy | Document ID: IBCS-COPYRIGHT-CONTENT-PROTECTION-POLICY-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.",
  "PAGE B  /  COPYRIGHT CONTENT PROTECTION POLICY",
  "49. FINAL CONTENT PROTECTION DECLARATION",
  "IB Cyber Security Private Limited protects and reserves all copyright and related rights that it lawfully owns or controls in its qualifying original content and materials.",
  "The Company may use reasonable technical, organizational, administrative and legal measures to identify, protect, monitor, document and respond to unauthorized use of its qualifying copyrighted content.",
  "Detection of a suspected copy, similarity or content match does not automatically establish infringement. Any legal determination shall depend upon applicable law, ownership or lawful control of the relevant rights, authorization, statutory exceptions, fair dealing or other permitted acts, and the facts of the particular matter.",
  "Third-party materials remain subject to their respective owners' rights and applicable licences. Statutory exceptions under Indian law remain unaffected.",
  "The Company reserves all copyright and related rights that it lawfully owns or controls and reserves all legally available remedies in respect of actionable infringement.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT CONTENT PROTECTION POLICY"
];
