export const contentData = [
  "PAGE A  /  COPYRIGHT ATTRIBUTION POLICY",
  "Copyright Attribution Policy",
  "Credit and attribution guidelines for third-party use of our content.",
  "1. PURPOSE OF THIS COPYRIGHT ATTRIBUTION POLICY",
  "This Copyright Attribution Policy (“Policy”) establishes the attribution and credit requirements applicable to qualifying original copyrighted works owned or lawfully controlled by IB Cyber Security Private Limited (“Company”).",
  "The purpose of this Policy is to establish a clear and consistent method for identifying the Company as the copyright owner or rights holder where attribution is required by applicable permission, licence, agreement or law.",
  "This Policy applies to qualifying original materials made available through or in connection with the official Website of IB Cyber Security Private Limited at https://ibcybersecurity.com (“Website”), to the extent that the Company lawfully owns or controls the relevant rights.",
  "This Policy shall be interpreted in accordance with the Copyright Act, 1957, as amended from time to time, and other applicable laws of India.",
  "2. COPYRIGHT OWNER",
  "The copyright owner identified under this Policy is: IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company).",
  "The Company reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its qualifying original works and materials.",
  "3. MATERIALS COVERED BY THIS POLICY",
  "This Policy may apply to qualifying original materials owned or lawfully controlled by the Company, including:",
  "• Original website text, sentences, paragraphs, articles, publications, educational & cyber-awareness materials• Original images, photographs, audio, videos, animations, graphics, illustrations, icons, symbols, & watermarks• Original branding, UI/UX creative expression, visual designs, source code, software, PDFs, documents, presentations, digital assets, & compilations",
  "Attribution requirements apply only to materials in which the Company lawfully owns or controls the relevant rights.",
  "PAGE B  /  COPYRIGHT ATTRIBUTION POLICY",
  "4. GENERAL ATTRIBUTION PRINCIPLE",
  "Where attribution is required by an applicable written permission, licence, agreement or applicable law, the user must provide appropriate and accurate attribution to the Company.",
  "Attribution should not:• Misrepresent ownership or misidentify copyright owner• Intentionally remove, conceal or alter required ownership info• Falsely imply endorsement, partnership or affiliation• Suggest user created the work or ownership has transferred",
  "5. STANDARD ATTRIBUTION FORMAT",
  "Unless specified otherwise by permission or licence, standard format:IB Cyber Security Private LimitedPublic / Brand Name: IBCSOfficial Website: https://ibcybersecurity.com",
  "Where a copyright notice is appropriate: © 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "6. COPYRIGHT NOTICE",
  "Where appropriate, Company-owned materials may carry: © 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "The copyright notice identifies claimed ownership and does not determine the legal status of third-party materials.",
  "PAGE A  /  COPYRIGHT ATTRIBUTION POLICY",
  "7. WRITTEN PERMISSION AND ATTRIBUTION",
  "Where the Company grants written permission to use a protected work, the recipient must comply strictly with the attribution conditions specified in the written permission.",
  "8. LICENCE-BASED ATTRIBUTION",
  "Licensees must comply with licence requirements regarding exact wording, placement, visibility, platform location, duration, copyright notice, and branding.",
  "9. ATTRIBUTION FOR WRITTEN CONTENT",
  "Attribution should identify: IB Cyber Security Private Limited | Official Website: https://ibcybersecurity.com.",
  "Users must not present Company-owned written content as their own original work.",
  "10. ATTRIBUTION FOR ARTICLES AND PUBLICATIONS",
  "Attribution should identify: IB Cyber Security Private Limited, work title, official Website (https://ibcybersecurity.com), and any licence conditions.",
  "PAGE B  /  COPYRIGHT ATTRIBUTION POLICY",
  "11. ATTRIBUTION FOR EDUCATIONAL MATERIALS",
  "Identify Company as source/owner: Source / Copyright: IB Cyber Security Private Limited | Official Website: https://ibcybersecurity.com",
  "12. ATTRIBUTION FOR IMAGES AND PHOTOGRAPHS",
  "Identify: IB Cyber Security Private Limited and © 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "13. ATTRIBUTION FOR GRAPHICS AND ILLUSTRATIONS",
  "Identify: IB Cyber Security Private Limited and copyright notice: © 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "14. ATTRIBUTION FOR AUDIO AND VIDEO",
  "Identify IB Cyber Security Private Limited specifying placement, display duration, description, copyright notice, and website reference.",
  "PAGE A  /  COPYRIGHT ATTRIBUTION POLICY",
  "15. ATTRIBUTION FOR ANIMATIONS AND MOTION GRAPHICS",
  "Identify: IB Cyber Security Private Limited | Official Website: https://ibcybersecurity.com or comply with written licence terms.",
  "16. ATTRIBUTION FOR SOURCE CODE AND SOFTWARE",
  "Identify: Copyright: IB Cyber Security Private Limited | Official Website: https://ibcybersecurity.com. Third-party components maintain separate attribution.",
  "17. ATTRIBUTION FOR PDFs AND DOCUMENTS",
  "Identify: IB Cyber Security Private Limited, document title, and official website https://ibcybersecurity.com.",
  "18. ATTRIBUTION FOR SOCIAL-MEDIA USE",
  "Identify: IB Cyber Security Private Limited | IBCS | https://ibcybersecurity.com. Reposts must not be presented as original work.",
  "PAGE B  /  COPYRIGHT ATTRIBUTION POLICY",
  "19. ATTRIBUTION FOR QUOTATIONS",
  "Quotations must identify source/owner, work title, website, and preserve context. Attribution does not replace permission where required.",
  "20. ATTRIBUTION FOR MODIFIED OR ADAPTED MATERIALS",
  "Authorized modifications must identify original work, Company ownership, and clearly indicate where material has been modified or adapted.",
  "21. ATTRIBUTION DOES NOT TRANSFER OWNERSHIP",
  "Attribution statements do not assign copyright, transfer ownership, grant additional rights, create broader licences, or authorize commercial use/modification.",
  "22. ATTRIBUTION DOES NOT SUBSTITUTE FOR PERMISSION",
  "Attribution alone does not constitute permission. “Credit to IB Cyber Security Private Limited” does not authorize copying or commercial use where permission is required.",
  "PAGE A  /  COPYRIGHT ATTRIBUTION POLICY",
  "23. PRESERVATION OF COPYRIGHT NOTICES",
  "Users must preserve copyright notices and ownership information associated with Company materials without unauthorized removal.",
  "24. ATTRIBUTION PLACEMENT",
  "Attribution should be visible and close to material: beneath images, in articles, video/audio credits, document acknowledgements, code comments, or captions.",
  "25. ACCURATE ATTRIBUTION",
  "Attribution must be accurate without misleading claims, false authorship, false endorsement, or false partnership claims.",
  "26. BRAND NAME AND ORGANIZATION NAME",
  "Organization Name: IB Cyber Security Private Limited | Public / Brand Name: IBCS. Name must not be altered misleadingly.",
  "PAGE B  /  COPYRIGHT ATTRIBUTION POLICY",
  "27. WEBSITE ATTRIBUTION",
  "Preferred reference: https://ibcybersecurity.com. Website reference identifies source but does not grant reproduction rights.",
  "28. WATERMARKS AND OWNERSHIP MARKINGS",
  "Users must comply with conditions concerning watermarks and ownership markings without unauthorized removal or concealment.",
  "29. THIRD-PARTY MATERIALS",
  "Google Fonts, open-source libraries, open-source frameworks, software components, licensed assets, and embedded media remain subject to third-party rights.",
  "30. THIRD-PARTY AND OPEN-SOURCE ATTRIBUTION",
  "Third-party licence attribution requirements must be satisfied independently and distinguished from Company attribution.",
  "PAGE A  /  COPYRIGHT ATTRIBUTION POLICY",
  "31. INCORRECT OR INCOMPLETE ATTRIBUTION",
  "Where authorized users provide incorrect or incomplete attribution, the Company may request corrective attribution.",
  "32. ATTRIBUTION CORRECTION REQUESTS",
  "The Company may request correction if identification is omitted, incorrect, misleading, or violates licence rules.",
  "33. FALSE OWNERSHIP CLAIMS",
  "Users must not falsely claim ownership, authorship or copyright in Company-owned original works.",
  "34. NO IMPLIED ENDORSEMENT",
  "Attribution must not falsely imply sponsorship, endorsement, partnership, certification, authorization, or official affiliation.",
  "PAGE B  /  COPYRIGHT ATTRIBUTION POLICY",
  "35. STATUTORY EXCEPTIONS AND LIMITATIONS",
  "Nothing in this Policy restricts statutory exceptions, fair dealing, compulsory licences, or statutory rights under Indian copyright law.",
  "36. COPYRIGHT REGISTRATION",
  "Policy & Document ID (IBCS-COPYRIGHT-ATTRIBUTION-POLICY-001) are internal control references, separate from government registration.",
  "37. COPYRIGHT INFRINGEMENT",
  "Unauthorized use outside permission or licence scope may constitute copyright infringement. Report to: copyrightreport@ibcybersecurity.com",
  "38. PERMISSION AND LICENSING CONTACT",
  "Permission or licensing requests should be submitted in writing to: hr@ibcybersecurity.com.",
  "PAGE A  /  COPYRIGHT ATTRIBUTION POLICY",
  "39. WEBSITE UNDER MAINTENANCE",
  "Temporary website maintenance, redesign, or updates do not constitute abandonment of copyright in original works.",
  "40. POLICY INTERPRETATION",
  "Interpreted consistently with Indian copyright law. Mandatory statutory legal provisions prevail over conflicting Policy terms.",
  "41. APPLICABLE INDIAN LAW",
  "Governed principally by the Copyright Act, 1957 (Sections 13, 14, 17, 18, 19, 30, 30A, 51, 52, 55, 57, 63). Section 57 recognizes author's special moral rights to attribution.",
  "42. GOVERNING LAW AND JURISDICTION",
  "Governed by Indian law. Jurisdiction resides in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "PAGE B  /  COPYRIGHT ATTRIBUTION POLICY",
  "43. OFFICIAL ATTRIBUTION INFORMATION",
  "Copyright Owner: IB Cyber Security Private Limited | Brand Name: IBCS | Official Website: https://ibcybersecurity.comStandard Notice: © 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "44. OFFICIAL CONTACT INFORMATION",
  "Permissions & Licensing: hr@ibcybersecurity.com | Infringement Reports: copyrightreport@ibcybersecurity.com | Legal Contact: legaldepartment@ibcybersecurity.com",
  "45. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited | Public / Brand Name: IBCS | Private Limited Company",
  "Official Website: https://ibcybersecurity.com | Emails: hr@ibcybersecurity.com | legaldepartment@ibcybersecurity.com | copyrightreport@ibcybersecurity.com | Phone:  | 8093424777",
  "PAGE A  /  COPYRIGHT ATTRIBUTION POLICY",
  "46. DOCUMENT CONTROL",
  "Document Title: Copyright Attribution Policy | Document ID: IBCS-COPYRIGHT-ATTRIBUTION-POLICY-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.",
  "47. COPYRIGHT STATEMENT",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "IB Cyber Security Private Limited reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its qualifying original works and materials.",
  "PAGE B  /  COPYRIGHT ATTRIBUTION POLICY",
  "48. FINAL ATTRIBUTION DECLARATION",
  "IB Cyber Security Private Limited requires accurate attribution where required by permission, licence, agreement, or law.",
  "Standard format: IB Cyber Security Private Limited | IBCS | https://ibcybersecurity.com.",
  "Notice: © 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "Attribution does not transfer copyright ownership or substitute for written permission. Users must not falsely claim ownership or remove required markings.",
  "Third-party materials remain subject to their respective owners' rights. Statutory exceptions under Indian law remain unaffected.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT ATTRIBUTION POLICY"
];
