export const contentData = [
  "PAGE A  /  COPYRIGHT INFRINGEMENT NOTICE",
  "Copyright Infringement Notice",
  "Report and action process for copyright violations and misuse.",
  "1. PURPOSE OF THIS INFRINGEMENT POLICY",
  "This Copyright Infringement Policy (“Policy”) establishes the principles and procedures followed by IB Cyber Security Private Limited (“Company”) in relation to suspected or alleged infringement of qualifying original copyrighted works owned or lawfully controlled by the Company.",
  "This Policy applies to qualifying copyright-protected materials made available through or in connection with the official Website of IB Cyber Security Private Limited at https://ibcybersecurity.com (“Website”), to the extent that the Company lawfully owns or controls the relevant copyright.",
  "The purpose of this Policy is to provide a clear mechanism for reporting suspected infringement, reviewing infringement allegations, requesting cessation or removal of unauthorized use, and pursuing legally available remedies where appropriate.",
  "This Policy shall be interpreted in accordance with the Copyright Act, 1957, as amended from time to time, and other applicable laws of India.",
  "2. COPYRIGHT OWNER & 3. MATERIALS COVERED",
  "Copyright Owner: IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company).",
  "Applies to website text, written content, articles, publications, educational & cyber-awareness materials, original images, audio, video, animations, graphics, illustrations, icons, symbols, watermark designs, branding materials, UI/UX creative expression, visual designs, source code, software, PDFs, documents, presentations, digital assets, compilations, and arrangements.",
  "PAGE B  /  COPYRIGHT INFRINGEMENT NOTICE",
  "4. WHAT CONSTITUTES INFRINGEMENT",
  "Unauthorized reproduction, publication, distribution of copies, public communication, adaptation, translation, commercial exploitation, derivative creation, source code copying, or media extraction without valid authorization constitutes copyright infringement.",
  "5. NO AUTOMATIC FINDING & 6. REPORTING INFRINGEMENT",
  "Not every unauthorized-looking use is infringement (statutory exceptions or third-party licences may apply). Suspected infringement may be reported to: copyrightreport@ibcybersecurity.com.",
  "7. REPORTING REQUIREMENTS & 8. GOOD-FAITH SUBMISSIONS",
  "Reports must include: reporter contact details, work ID, protection basis, ownership proof, URL of infringing material, similarity description, screenshot evidence, and accuracy statement. Good-faith reporting is strictly required.",
  "9. REVIEW OF REPORTS & 10. INFO REQUESTS",
  "The Company evaluates reports considering copyright subsistence, ownership proof, licence existence, statutory exceptions, and extent of use. Additional information or evidence may be requested.",
  "PAGE A  /  COPYRIGHT INFRINGEMENT NOTICE",
  "11. NOTICE TO ALLEGED INFRINGER & 12. C&D COMMUNICATIONS",
  "The Company may issue written notices requesting: cessation of unauthorized use, removal of infringing material, discontinuation of distribution/commercial exploitation, and compliance confirmation. Cease-and-desist communications are discretionary.",
  "13. IMMEDIATE LEGAL ACTION & 14. VOLUNTARY RESOLUTION",
  "Immediate legal action without prior warning may be taken for: commercial exploitation, repeated infringement, large-scale distribution, or evidence-preservation risks. Voluntary negotiation may be attempted where appropriate.",
  "15. REPEATED INFRINGEMENT & 16. PLATFORM COMPLAINTS",
  "Repeated infringement triggers escalated legal remedies. The Company submits takedown requests to third-party platforms, hosting services, and search engines for infringing content.",
  "17. FALSE OWNERSHIP CLAIMS & 18. WATERMARK REMOVAL",
  "False representations claiming ownership of Company materials and unauthorized removal/concealment of copyright watermarks will be met with direct legal objections and claims.",
  "PAGE B  /  COPYRIGHT INFRINGEMENT NOTICE",
  "19. COMMERCIAL INFRINGEMENT",
  "Unauthorized commercial exploitation constitutes a serious violation. The Company considers commercial scale, duration, and financial impact when determining appropriate legal remedies.",
  "20. SOURCE CODE & 21. DIGITAL MEDIA INFRINGEMENT",
  "Unauthorized copying, reproduction, distribution, modification, or commercial exploitation of protected source code, scripts, images, audio, video, animations, or graphics constitutes actionable infringement.",
  "22. THIRD-PARTY EXCLUSIONS & 23. STATUTORY EXCEPTIONS",
  "Google Fonts, open-source libraries, and third-party assets are excluded. Statutory fair dealing and permitted acts under Indian copyright law remain completely unrestricted.",
  "24. REGISTRATION & 25. EVIDENCE RECORDS",
  "Document ID (IBCS-COPYRIGHT-INFRINGEMENT-POLICY-001) is an internal document control reference. The Company maintains logs of original creation, permissions, and enforcement records.",
  "PAGE A  /  COPYRIGHT INFRINGEMENT NOTICE",
  "26. NO WAIVER OF RIGHTS",
  "Failure to immediately object to an unauthorized use does not constitute consent, permission, licence, assignment, waiver of copyright, or abandonment of rights.",
  "27. REMEDIES FRAMEWORK & 28. CIVIL REMEDIES",
  "Available remedies: injunctive relief, damages, account of profits, civil remedies, criminal remedies, statutory relief, platform complaint remedies, and content removal requests under Indian copyright law.",
  "29. CRIMINAL REMEDIES & 30. STATUTORY RELIEF",
  "Reserves the right to pursue or support criminal remedies under statutory provisions for criminal offences under Indian law, alongside any other statutory relief available.",
  "31. AUTHORITY COOPERATION & 32. GOOD-FAITH ENFORCEMENT",
  "Cooperates with competent courts, law-enforcement agencies, government authorities, and hosting platforms. Rights are enforced strictly in good faith in accordance with applicable law.",
  "PAGE B  /  COPYRIGHT INFRINGEMENT NOTICE",
  "33. MAINTENANCE & 34. SIMILARITY STANDARDS",
  "Temporary website maintenance, redesign, migration, or content revision does not constitute abandonment of copyright. Merely having similar generic words or ideas does not establish infringement without protected expression copying.",
  "35. POLICY INTERPRETATION & 36. APPLICABLE INDIAN LAW",
  "Interpreted consistently with Indian copyright law (Copyright Act, 1957, Sections 13, 14, 17, 51, 52, 55, 63). Mandatory statutory provisions prevail in case of conflict.",
  "37. GOVERNING LAW AND JURISDICTION",
  "Governed by the laws of India. Legal matters reside in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "PAGE A  /  COPYRIGHT INFRINGEMENT NOTICE",
  "38. OFFICIAL INFRINGEMENT REPORTING CONTACT",
  "Infringement Reports: copyrightreport@ibcybersecurity.comPermission Requests: hr@ibcybersecurity.comLegal Contact: legaldepartment@ibcybersecurity.com",
  "39. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company)Official Website: https://ibcybersecurity.com | Phone:  | 8093424777",
  "40. DOCUMENT CONTROL & 41. COPYRIGHT STATEMENT",
  "Document Title: Copyright Infringement Policy | ID: IBCS-COPYRIGHT-INFRINGEMENT-POLICY-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.© 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "PAGE B  /  COPYRIGHT INFRINGEMENT NOTICE",
  "42. FINAL INFRINGEMENT DECLARATION",
  "IB Cyber Security Private Limited takes the protection of its qualifying original copyrighted works seriously.",
  "Reserves the right to review suspected infringement and request cessation/removal, issue cease-and-desist communications, pursue platform complaints, seek civil relief, and pursue criminal remedies.",
  "Respects third-party copyright, licences, statutory exceptions, fair dealing, and limitations under Indian law.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT INFRINGEMENT POLICY"
];
