export const contentData = [
  "PAGE A  /  COPYRIGHT LEGAL DISCLAIMER",
  "Copyright Legal Disclaimer",
  "Limitations of liability and legal information related to our copyrighted materials.",
  "1. PURPOSE OF THIS COPYRIGHT DISCLAIMER",
  "This Copyright Disclaimer (“Disclaimer”) is issued by IB Cyber Security Private Limited (“Company”) in connection with its official Website available at https://ibcybersecurity.com (“Website”).",
  "The purpose of this Disclaimer is to clarify the scope and limitations of the Company’s copyright claims and to distinguish Company-owned original materials from third-party materials, non-copyrightable subject matter, statutory rights, licences and other legally recognized limitations.",
  "This Disclaimer shall be read together with the applicable laws of India, including the Copyright Act, 1957, as amended from time to time.",
  "2. COPYRIGHT OWNER",
  "The copyright owner identified for qualifying original works lawfully owned or controlled by the Company is:",
  "IB Cyber Security Private LimitedPublic / Brand Name: IBCS | Organization Type: Private Limited Company",
  "The Company asserts and reserves the copyright and related rights that it lawfully owns or controls in its qualifying original works and materials.",
  "3. SCOPE OF THE FOUNDATION’S COPYRIGHT CLAIM",
  "The Company may claim copyright protection, to the extent legally available and lawfully owned or controlled by it, in original materials associated with the Website, including:",
  "• Original website text, written content, sentences, paragraphs, articles, publications, educational & cyber-awareness materials• Original images, photographs, audio, videos, animations, graphics, illustrations, icons, symbols, watermark designs, & branding materials• Original UI/UX creative expression, visual designs, source code, software, PDFs, documents, presentations, digital assets, compilations, & arrangements",
  "The Company’s copyright claim applies only to the extent that the particular material qualifies for copyright protection and the Company lawfully owns or controls the relevant rights.",
  "PAGE B  /  COPYRIGHT LEGAL DISCLAIMER",
  "4. DISCLAIMER REGARDING INDIVIDUAL WORDS, FACTS AND IDEAS",
  "The Company does not claim copyright merely over: individual words, short phrases, names, facts, general ideas, concepts, methods, procedures, systems, processes, general information, or common knowledge.",
  "Copyright protection, where applicable, concerns qualifying original expression and creative works rather than underlying facts, ideas, concepts or other subject matter that is not protected by copyright law.",
  "5. DISCLAIMER REGARDING MEANING AND INFORMATION",
  "The Company may own copyright in the original expression, wording, selection and arrangement used to communicate information through the Website.",
  "However, the Company does not claim exclusive copyright over underlying facts, general information, ideas, concepts or meanings that are not independently protected by copyright.",
  "The existence of copyright in a particular work does not necessarily mean that every fact or idea contained within that work is exclusively owned by the Company.",
  "6. THIRD-PARTY MATERIALS DISCLAIMER",
  "The Website may contain, use, display, link to, embed or incorporate materials owned or licensed by third parties (Google Fonts, open-source libraries, open-source frameworks, third-party software components, licensed assets, third-party services, embedded materials).",
  "The Company does not claim ownership of third-party materials. Third-party materials remain subject to the copyright, trademark, licence and other intellectual-property rights of their respective owners.",
  "PAGE A  /  COPYRIGHT LEGAL DISCLAIMER",
  "7. THIRD-PARTY LICENCES",
  "Third-party materials used on the Website may be subject to separate licence terms and conditions. Users are responsible for complying with the applicable licence terms governing third-party materials.",
  "Nothing in this Disclaimer grants any User a licence to use third-party materials beyond the rights granted by their respective owners or applicable law.",
  "8. OPEN-SOURCE SOFTWARE DISCLAIMER",
  "The Website may use open-source software, libraries, frameworks or components. The Company does not claim ownership of third-party open-source software merely because such software is incorporated into or used by the Website.",
  "Open-source materials remain subject to their respective licences. Any original code, modifications or contributions in which the Company independently owns copyright shall remain subject to Company rights.",
  "9. GOOGLE FONTS AND THIRD-PARTY SERVICES",
  "The Website may use Google Fonts and other third-party services or resources. The Company does not claim ownership of third-party services, fonts, libraries, frameworks or resources.",
  "Such materials remain subject to the rights and applicable terms of their respective owners or providers.",
  "10. EXTERNAL LINKS DISCLAIMER",
  "The Website may contain links to external third-party websites. The Company does not claim copyright ownership over content hosted on external websites.",
  "Third-party websites remain subject to their respective owners' terms. Presence of an external link does not constitute ownership, endorsement, sponsorship or authorization.",
  "PAGE B  /  COPYRIGHT LEGAL DISCLAIMER",
  "11. USER-GENERATED OR THIRD-PARTY SUBMISSIONS",
  "Where the Website permits users or third parties to submit or upload content, such content shall not automatically become Company copyright property unless transferred by a valid legal arrangement.",
  "Copyright ownership in third-party submissions shall remain with the lawful owner.",
  "12. NO CLAIM OVER THIRD-PARTY COPYRIGHT",
  "The Company expressly disclaims ownership of copyright in materials that belong to third parties. Where third-party materials are displayed alongside Company materials, ownership rights remain separate.",
  "13. NO IMPLIED LICENCE",
  "Website accessibility, viewing, linking, URL sharing, or temporary display does not automatically grant a licence to reproduce, modify, distribute, publish, adapt or commercially exploit material.",
  "Any licence or permission granted by the Company shall be subject to express written authorization.",
  "14. PERSONAL VIEWING AND ACCESS",
  "Users may access and view publicly available Website materials for legitimate personal and informational purposes, subject to applicable law.",
  "Such access does not constitute copyright transfer, assignment, commercial licence, or reproduction permission.",
  "PAGE A  /  COPYRIGHT LEGAL DISCLAIMER",
  "15. STATUTORY EXCEPTIONS AND LIMITATIONS",
  "Nothing in this Disclaimer is intended to restrict any statutory exception, limitation, fair dealing provision, permitted act or other legal protection that cannot lawfully be restricted under Indian law.",
  "16. FAIR DEALING AND STATUTORY PERMITTED USES",
  "Where a statutory exception or permitted use under the Copyright Act, 1957 applies, such use shall remain subject to all prescribed statutory conditions.",
  "Any use falling outside an applicable statutory exception remains subject to copyright owned or controlled by IB Cyber Security Private Limited.",
  "17. SCREENSHOTS AND REPRODUCTIONS",
  "Screenshots, screen recordings, downloads, or reproductions of Website materials may involve copyright-protected works.",
  "Public publication, commercial use, substantial reproduction, modification, or redistribution of protected Company materials requires written permission.",
  "18. COMMERCIAL USE DISCLAIMER",
  "Commercial use of qualifying Company-owned copyrighted materials is not authorized merely because materials are publicly accessible. Prior written permission must be obtained from: hr@ibcybersecurity.com",
  "PAGE B  /  COPYRIGHT LEGAL DISCLAIMER",
  "19. COPYRIGHT REGISTRATION DISCLAIMER",
  "This Disclaimer and internal Document ID (IBCS-COPYRIGHT-DISCLAIMER-001) do not, by themselves, constitute a Government of India copyright registration certificate.",
  "Internal document control numbers shall not be represented as official government registration numbers.",
  "20. NO GOVERNMENT AUTHORIZATION OR ENDORSEMENT CLAIM",
  "Nothing in this Disclaimer should be interpreted as claiming that the Government of India or any government authority has approved, endorsed, certified or registered this Disclaimer.",
  "Website documents are organizational legal documents and do not become government documents merely because they refer to Indian copyright law.",
  "21. COPYRIGHT NOTICE AND WATERMARK DISCLAIMER",
  "The Company may display copyright notices or watermarks (© 2026 IB Cyber Security Private Limited. All Rights Reserved.). Absence of a notice does not determine copyright subsistence.",
  "22. WEBSITE DESIGN AND FUNCTIONALITY DISCLAIMER",
  "The Company may claim copyright in qualifying original creative expression forming part of its Website design. Functional concepts, methods, and technical features remain excluded.",
  "PAGE A  /  COPYRIGHT LEGAL DISCLAIMER",
  "23. SOURCE CODE AND SOFTWARE DISCLAIMER",
  "The Company may claim copyright in qualifying original source code and software-related works that it lawfully owns or controls.",
  "Third-party libraries, frameworks, and open-source software remain subject to their respective licences and ownership rights.",
  "24. NO WARRANTY OF EXCLUSIVITY FOR NON-PROTECTABLE ELEMENTS",
  "The Company does not represent that every element appearing on the Website is independently protected by copyright. Generic, functional, licensed, or public elements remain outside copyright protection.",
  "25. WEBSITE UNDER MAINTENANCE",
  "The official Website, https://ibcybersecurity.com, may currently be under maintenance, development, redesign, migration, or content updates.",
  "Temporary unavailability or modification of content does not constitute abandonment of copyright in qualifying original works.",
  "PAGE B  /  COPYRIGHT LEGAL DISCLAIMER",
  "26. COPYRIGHT INFRINGEMENT DISCLAIMER",
  "Unauthorized use of qualifying Company-owned original works may constitute copyright infringement where legal requirements are satisfied under Indian law.",
  "27. INFRINGEMENT REPORTING",
  "Suspected infringement may be reported to: copyrightreport@ibcybersecurity.com including reporter contact info, work ID, location URL, infringement description, evidence, and accuracy confirmation.",
  "28. WRITTEN PERMISSION",
  "Permission requests must be submitted in writing to: hr@ibcybersecurity.com detailing material, proposed use, medium, commercial status, and duration. Silence does not constitute permission or waiver.",
  "29. RESERVATION OF RIGHTS",
  "IB Cyber Security Private Limited reserves all copyright and related intellectual-property rights that it lawfully owns or controls under applicable law.",
  "PAGE A  /  COPYRIGHT LEGAL DISCLAIMER",
  "30. APPLICABLE INDIAN LAW",
  "This Disclaimer is made with reference to the copyright framework applicable in India, principally the Copyright Act, 1957, as amended (Sections 13, 14, 17, 51, 52, 55).",
  "Statutory provisions and judicial interpretation of Indian law shall prevail over this Disclaimer in the event of inconsistency.",
  "31. GOVERNING LAW AND JURISDICTION",
  "Governed and interpreted in accordance with the laws of India.",
  "Matters arising from or relating to this Disclaimer may be brought before competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "32. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited | Public / Brand Name: IBCS | Private Limited Company",
  "Official Website: https://ibcybersecurity.com | Emails: hr@ibcybersecurity.com | legaldepartment@ibcybersecurity.com | copyrightreport@ibcybersecurity.com | Phone:  | 8093424777",
  "PAGE B  /  COPYRIGHT LEGAL DISCLAIMER",
  "33. DOCUMENT CONTROL",
  "Document Title: Copyright Disclaimer | Document ID: IBCS-COPYRIGHT-DISCLAIMER-001 | Version: 1.0 | Effective Date: 26 September 2026 | Last Updated: 26 September 2026.",
  "34. COPYRIGHT STATEMENT",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "IB Cyber Security Private Limited reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its qualifying original works and materials.",
  "35. FINAL DISCLAIMER",
  "IB Cyber Security Private Limited provides this Copyright Disclaimer to clearly distinguish its lawful copyright claims from third-party rights, non-copyrightable subject matter, applicable licences and statutory exceptions.",
  "The Company claims and reserves copyright in its qualifying original works and materials only to the extent that copyright is legally available and the Company lawfully owns or controls the applicable rights.",
  "Nothing in this Disclaimer shall be interpreted as: a claim over third-party materials; a claim over unprotectable facts/ideas; a government certificate claim; a government authorization claim; a waiver of statutory exceptions; or a restriction of non-restrictable rights.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT DISCLAIMER"
];
