export const contentData = [
  "PAGE A  /  COPYRIGHT PROTECTION NOTICE",
  "Copyright Protection Notice",
  "Information on how we protect our creative works and prevent unauthorized use.",
  "1. PURPOSE OF THIS NOTICE",
  "This Copyright Protection Notice (“Notice”) establishes the copyright-protection framework applicable to qualifying original works and materials owned or lawfully controlled by IB Cyber Security Private Limited (“Company”) and made available through or in connection with its official Website at https://ibcybersecurity.com (“Website”).",
  "The purpose of this Notice is to provide clear public notice that the Company reserves and protects the copyright and related intellectual-property rights that it lawfully owns or controls in its original works.",
  "This Notice shall be interpreted in accordance with the Copyright Act, 1957, other applicable laws of India, valid third-party rights, applicable licences and statutory exceptions and limitations.",
  "2. COPYRIGHT OWNER",
  "The copyright owner identified under this Notice is: IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company).",
  "The Company reserves all copyright and related rights that it lawfully owns or controls in qualifying original works associated with the Website.",
  "3. SCOPE OF COPYRIGHT PROTECTION",
  "Protection applies to original website text, written content, articles, publications, educational & cyber-awareness materials, original images, photographs, audio, videos, animations, graphics, illustrations, icons, symbols, watermark designs, branding materials, UI/UX creative expression, visual designs, source code, software, documents, PDFs, presentations, digital assets, compilations, and arrangements.",
  "PAGE B  /  COPYRIGHT PROTECTION NOTICE",
  "4. PROTECTION OF WRITTEN CONTENT",
  "The Company protects its qualifying original written expression appearing on or distributed through the Website. Unauthorized reproduction, republication, substantial copying, distribution, adaptation or commercial exploitation is prohibited unless authorized.",
  "5. PROTECTION OF WEBSITE DESIGN AND UI/UX",
  "The Company protects qualifying original creative elements of its Website design and user experience, including page designs, visual layouts, UI/UX expression, component arrangements, graphical compositions, interaction designs, visual hierarchy, and navigation presentation.",
  "6. GRAPHICS, IMAGES & ARTWORK & 7. AUDIO/VIDEO",
  "Original graphics, images, photographs, illustrations, audio, and video materials owned or lawfully controlled by the Company are protected. Users must not reproduce, redistribute, commercially exploit, modify or republish protected materials without required authorization.",
  "8. ANIMATIONS & 9. SYMBOLS, ICONS & WATERMARKS",
  "Qualifying original animations, motion graphics, interface icons, graphical marks, watermark designs, and visual identification elements are protected by applicable copyright law.",
  "PAGE A  /  COPYRIGHT PROTECTION NOTICE",
  "10. SOURCE CODE AND SOFTWARE",
  "Qualifying original source code and software-related works owned or lawfully controlled by the Company are protected under applicable copyright law, including scripts, modules, components, implementations, and documentation.",
  "11. DIGITAL DOCUMENTS & EDUCATIONAL MATERIALS",
  "Original PDFs, documents, presentations, guides, manuals, educational resources, cyber-awareness materials and digital works owned or lawfully controlled by the Company are protected under applicable law.",
  "12. COMPILATIONS & 13. WEBSITE COMBINATION",
  "Claims copyright protection in qualifying original compilations, selections, arrangements, and creative combinations of written content, visual elements, graphics, images, audio, video, animations, UI/UX elements, and digital assets.",
  "14. PROHIBITED UNAUTHORIZED USE",
  "Prohibits: copying protected materials, reproducing substantial content, unauthorized republishing, downloading/redistributing for unauthorized purposes, creating derivative works, commercial exploitation, scraping, or removing notices.",
  "PAGE B  /  COPYRIGHT PROTECTION NOTICE",
  "15. PERSONAL VIEWING AND ACCESS",
  "Users may access and view publicly available Website content for legitimate personal/informational purposes. Access does not constitute copyright transfer, commercial licence, or reproduction permission.",
  "16. URL SHARING AND LINKING",
  "Users may share the official Website URL and provide links directing users to the Website. Linking does not grant permission to copy content, republish materials, or mirror the Website.",
  "17. SOCIAL MEDIA & 18. SCREENSHOTS",
  "Reposting materials on social media or publishing screenshots requires written permission and proper attribution, unless using platform native share functions.",
  "19. COMMERCIAL USE & 20. MODIFICATION LIMITS",
  "Commercial use, selling, paid integration, editing, adaptation, translation, rebranding, redesigning, or creating derivative works is prohibited without prior written authorization.",
  "PAGE A  /  COPYRIGHT PROTECTION NOTICE",
  "21. DOWNLOAD & REDISTRIBUTION RESTRICTIONS",
  "Provided downloads remain subject to applicable terms. Materials must not be redistributed, commercially exploited, or modified beyond granted rights.",
  "22. COPYRIGHT MARKINGS AND WATERMARKS",
  "Copyright notices, watermarks, and ownership markings (e.g. © 2026 IB Cyber Security Private Limited) must not be removed, concealed, or altered without authorization.",
  "23. THIRD-PARTY MATERIALS & 24. STATUTORY EXCEPTIONS",
  "Third-party materials (Google Fonts, open-source libraries) remain subject to their respective owners' terms. Statutory fair dealing and permitted acts under Indian law remain unrestricted.",
  "25. INFRINGEMENT & 26. ENFORCEMENT REMEDIES",
  "Unauthorized use constitutes infringement. The Company reserves all civil remedies, legal notices, cease-and-desist actions, takedown requests, and statutory remedies under Indian law.",
  "PAGE B  /  COPYRIGHT PROTECTION NOTICE",
  "27. COPYRIGHT INFRINGEMENT REPORTING",
  "Infringement reports should be submitted to: copyrightreport@ibcybersecurity.com with work details, URL, ownership proof, and accuracy statement.",
  "28. WRITTEN PERMISSION PROCEDURE",
  "Permission requests must be submitted in writing to: hr@ibcybersecurity.com. Silence or delay does not constitute permission, consent, or waiver.",
  "29. NO IMPLIED LICENCE & 30. MAINTENANCE",
  "Public availability does not create an implied licence. Temporary website maintenance, redesign, or migration does not constitute abandonment of copyright.",
  "31. RESERVATION OF RIGHTS & 32. REGISTRATION",
  "Reserves all copyright and related rights. Document ID (IBCS-COPYRIGHT-PROTECTION-NOTICE-001) is an internal document control reference.",
  "PAGE A  /  COPYRIGHT PROTECTION NOTICE",
  "33. APPLICABLE INDIAN LAW & 34. JURISDICTION",
  "Governed by the Copyright Act, 1957 (Sections 13, 14, 17, 51, 52, 55). Jurisdiction resides in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "35. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited (Brand Name: IBCS | Private Limited Company)Emails: hr@ibcybersecurity.com | legaldepartment@ibcybersecurity.com | copyrightreport@ibcybersecurity.com | Phone:  | 8093424777",
  "36. DOCUMENT CONTROL & 37. STATEMENT",
  "Document Title: Copyright Protection Notice | ID: IBCS-COPYRIGHT-PROTECTION-NOTICE-001 | Version: 1.0 | Effective: 26 September 2026.© 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "PAGE B  /  COPYRIGHT PROTECTION NOTICE",
  "38. FINAL COPYRIGHT PROTECTION DECLARATION",
  "IB Cyber Security Private Limited hereby formally declares that its qualifying original works and materials are protected by the rights available under applicable copyright law to the extent such rights are legally vested in and owned or lawfully controlled by the Company.",
  "This protection extends to original written content, creative expression, images, photographs, audio, videos, animations, graphics, illustrations, symbols, icons, watermark designs, branding materials, UI/UX creative expression, visual designs, source code, software-related works, documents, educational materials, digital assets, compilations, selections, arrangements and other qualifying original works.",
  "Third-party materials remain excluded from the Company’s ownership claim and remain subject to their respective owners’ rights and applicable licences.",
  "Unauthorized use of protected Company-owned original materials may result in appropriate legal action and remedies available under applicable law.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT PROTECTION NOTICE"
];
