export const contentData = [
  "PAGE A  /  COPYRIGHT ENFORCEMENT POLICY",
  "Copyright Enforcement Policy",
  "Steps and actions taken to enforce our copyright rights.",
  "1. PURPOSE OF THIS COPYRIGHT ENFORCEMENT POLICY",
  "This Copyright Enforcement Policy (“Policy”) establishes the framework adopted by IB Cyber Security Private Limited (“Company”) for receiving, reviewing and responding to reports concerning suspected unauthorized use of qualifying copyrighted works owned or lawfully controlled by the Company.",
  "The purpose of this Policy is to protect the Company’s lawful copyright interests by establishing a structured process for: receiving reports, reviewing ownership, requesting additional info, preserving evidence, seeking voluntary compliance, issuing notices, submitting platform complaints, and pursuing civil/criminal remedies.",
  "This Policy applies to qualifying original copyrighted materials owned or lawfully controlled by the Company and made available through or in connection with its official Website at https://ibcybersecurity.com (“Website”).",
  "Interpreted in accordance with the Copyright Act, 1957, as amended from time to time, and other applicable laws of India.",
  "2. COPYRIGHT OWNER",
  "Legal Organization: IB Cyber Security Private Limited",
  "Public / Brand Name: IBCS",
  "Organization Type: Private Limited Company",
  "The Company reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its qualifying original works.",
  "PAGE B  /  COPYRIGHT ENFORCEMENT POLICY",
  "3. MATERIALS PROTECTED UNDER THIS POLICY (PART I)",
  "Materials subject to enforcement under this Policy may include:• Original website text and written content• Original articles and publications• Educational materials• Cyber-awareness materials• Original images and photographs• Original graphics and illustrations• Original icons and symbols• Original audio• Original videos• Original animations• Original visual designs",
  "PAGE A  /  COPYRIGHT ENFORCEMENT POLICY",
  "3. MATERIALS PROTECTED UNDER THIS POLICY (PART II)",
  "Continued list of protectable original materials:• Original branding materials and watermark designs• Original UI/UX creative expression• Original source code and software-related works• Original PDFs, documents, and presentations• Original digital assets• Original compilations and arrangements, where legally protectable• Other qualifying literary, artistic, audiovisual, software or digital works",
  "Third-party materials remain subject to their respective owners’ rights and applicable licences.",
  "4. THIRD-PARTY MATERIALS",
  "The Website may use third-party materials (Google Fonts, open-source libraries, frameworks, third-party software, licensed media, embedded content). The Company claims no ownership over third-party materials. Enforcement under this Policy is limited to rights lawfully owned or controlled by the Company.",
  "PAGE B  /  COPYRIGHT ENFORCEMENT POLICY",
  "5. OPEN-SOURCE MATERIALS",
  "Open-source software remains subject to applicable licences. Use does not transfer ownership to the Company, nor does this Policy override open-source licence terms. Where a report concerns a third-party or open-source component, the relevant rights holder or licence governs.",
  "6. BASIS FOR COPYRIGHT ENFORCEMENT REPORTS",
  "Reporters should have a reasonable basis for believing use is unauthorized and should not knowingly submit false information. Submission of a report does not automatically establish infringement.",
  "7. COPYRIGHT ENFORCEMENT REPORTING",
  "Suspected unauthorized use involving Company-owned original materials may be reported in writing to: copyrightreport@ibcybersecurity.com.",
  "PAGE A  /  COPYRIGHT ENFORCEMENT POLICY",
  "8. INFORMATION RECOMMENDED FOR A COPYRIGHT ENFORCEMENT REPORT",
  "Reports should include: work identification, material description, URL/location, use description, date identified, evidence/screenshots, explanation of unauthorized nature, contact details, and authorization details where submitted on behalf of another rights holder.",
  "9. REPORT REVIEW",
  "The Company evaluates reports considering ownership info, creation/publication records, permissions, licences, work nature, reported use nature, statutory exceptions, and third-party rights.",
  "PAGE B  /  COPYRIGHT ENFORCEMENT POLICY",
  "10. REQUEST FOR ADDITIONAL INFORMATION",
  "The Company may request ownership records, URLs, screenshots, publication dates, licence/permission records, correspondence, technical info, and authorization documents.",
  "11. RESPONSE TO SUSPECTED UNAUTHORIZED USE",
  "Possible actions: contacting parties, requesting voluntary removal/cessation, attribution correction, discontinuation of distribution, cease-and-desist communications, platform/hosting complaints, or civil/criminal proceedings.",
  "PAGE A  /  COPYRIGHT ENFORCEMENT POLICY",
  "12. NOTICE AND VOLUNTARY COMPLIANCE",
  "Where appropriate, the Company provides an opportunity to voluntarily remove content, cease distribution, or correct attribution before pursuing legal steps.",
  "13. CEASE-AND-DESIST COMMUNICATION",
  "Where legally justified, C&D communications specify protected work, claimed rights, reported activity, requested corrective action, response period, and contact details.",
  "PAGE B  /  COPYRIGHT ENFORCEMENT POLICY",
  "14. PLATFORM AND HOSTING COMPLAINTS",
  "Complaints may be submitted to social platforms, video hosts, search engines, web hosts, domain registrars, application platforms, and intermediaries.",
  "15. PRESERVATION OF EVIDENCE",
  "The Company preserves screenshots, URLs, content captures, publication dates, web logs, correspondence, permission/licence records, and technical evidence for enforcement purposes.",
  "PAGE A  /  COPYRIGHT ENFORCEMENT POLICY",
  "16. LEGAL REMEDIES",
  "Available remedies: injunctive relief, monetary damages, account of profits, recovery/delivery-up of infringing copies, and statutory remedies under Indian law.",
  "17. STATUTORY COPYRIGHT REMEDIES",
  "The Company relies upon remedies available under applicable provisions of the Copyright Act, 1957, where legal requirements are satisfied.",
  "18. RIGHTS RELATING TO INFRINGING COPIES",
  "Exercises rights available under Indian copyright law concerning infringing copies and materials used in producing such copies.",
  "PAGE B  /  COPYRIGHT ENFORCEMENT POLICY",
  "19. CRIMINAL ENFORCEMENT",
  "Where conduct falls within criminal offences under Indian law, the Company may support criminal enforcement through competent authorities.",
  "20. CIVIL ENFORCEMENT",
  "Pursues civil proceedings before courts having jurisdiction based on ownership, evidence, licences, statutory exceptions, and defences.",
  "21. NO AUTOMATIC DETERMINATION OF INFRINGEMENT",
  "A report or notice does not automatically establish infringement prior to evaluation by a competent authority or court.",
  "PAGE A  /  COPYRIGHT ENFORCEMENT POLICY",
  "22. STATUTORY EXCEPTIONS AND LIMITATIONS",
  "Does not restrict fair dealing, Section 52 permitted acts, compulsory licences, statutory licences, or private personal uses under Indian law.",
  "23. GOOD-FAITH ENFORCEMENT",
  "Reviews reports in good faith and withdraws complaints if material demonstrates that use is authorized, lawful, or not actionable.",
  "24. FALSE OR MISLEADING REPORTS",
  "Knowingly false, fraudulent or materially misleading copyright reports are prohibited and actionable.",
  "PAGE B  /  COPYRIGHT ENFORCEMENT POLICY",
  "25. NO WAIVER OF RIGHTS",
  "Failure to immediately respond to unauthorized use does not constitute consent, authorization, waiver of copyright, or transfer of ownership.",
  "26. NO IMPLIED LICENCE",
  "Website availability grants no implied licence to reproduce, distribute, modify, or commercially exploit protected materials.",
  "27. COPYRIGHT REGISTRATION",
  "Document ID (IBCS-COPYRIGHT-ENFORCEMENT-POLICY-001) is an internal reference separate from government copyright registration.",
  "PAGE A  /  COPYRIGHT ENFORCEMENT POLICY",
  "28. WEBSITE UNDER MAINTENANCE",
  "Temporary website maintenance or redesign does not constitute abandonment of copyright in qualifying works.",
  "29. POLICY INTERPRETATION",
  "Interpreted consistently with Indian copyright law. Mandatory legal provisions prevail in case of conflict.",
  "30. APPLICABLE INDIAN LAW",
  "Principally governed by the Copyright Act, 1957 (Sections 13, 14, 17, 18, 19, 30, 30A, 51, 52, 55, 58, 63).",
  "PAGE B  /  COPYRIGHT ENFORCEMENT POLICY",
  "31. GOVERNING LAW AND JURISDICTION",
  "Governed by Indian law. Jurisdiction resides in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "32. COPYRIGHT PERMISSION CONTACT",
  "Permission & Licensing: hr@ibcybersecurity.com",
  "33. COPYRIGHT ENFORCEMENT REPORTING CONTACT",
  "Enforcement Reports: copyrightreport@ibcybersecurity.com",
  "34. LEGAL CONTACT",
  "Legal Correspondence: legaldepartment@ibcybersecurity.com",
  "PAGE A  /  COPYRIGHT ENFORCEMENT POLICY",
  "35. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company)Phone:  | 8093424777",
  "36. DOCUMENT CONTROL",
  "Document Title: Copyright Enforcement Policy | ID: IBCS-COPYRIGHT-ENFORCEMENT-POLICY-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.",
  "37. COPYRIGHT STATEMENT",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.IB Cyber Security Private Limited reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its qualifying original works and materials.",
  "PAGE B  /  COPYRIGHT ENFORCEMENT POLICY",
  "38. FINAL ENFORCEMENT DECLARATION",
  "IB Cyber Security Private Limited takes the enforcement of its qualifying original copyrighted works seriously.",
  "Reserves the right to review suspected infringement and request cessation/removal, issue cease-and-desist communications, pursue platform complaints, seek civil relief, and pursue criminal remedies.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT ENFORCEMENT POLICY"
];
