export const contentData = [
  "PAGE A  /  DIGITAL CONTENT COPYRIGHT NOTICE",
  "Digital Content Copyright Notice",
  "Protection for images, videos, audio, PDFs, graphics and multimedia content.",
  "1. COPYRIGHT NOTICE",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "The original copyrighted materials contained on or made available through the official website of IB Cyber Security Private Limited at https://ibcybersecurity.com (“Website”) are protected under applicable copyright law to the extent such protection subsists and the relevant rights are lawfully held or controlled by IB Cyber Security Private Limited (“Company”).",
  "2. ORIGINAL WEBSITE CONTENT",
  "The Website contains original content and materials created through company-owned/internal development and maintained for the Company, subject to applicable third-party materials, licences, permissions and other lawful rights.",
  "Copyright protection applies only to those aspects of the Website that qualify for protection under applicable law.",
  "Copyright protection does not extend to ideas, facts, procedures, methods, concepts, systems or other subject matter that is not protectable under applicable copyright law.",
  "3. WEBSITE TEXT AND CONTENT",
  "Original written content appearing on the Website, including qualifying articles, descriptions, educational materials, informational materials, statements, and other literary works, may be protected by copyright to the extent permitted by applicable law.",
  "Unauthorized reproduction, republication or other restricted use may constitute copyright infringement where the applicable legal requirements are satisfied.",
  "4. IMAGES, GRAPHICS AND VISUAL MATERIALS",
  "Qualifying original images, photographs, graphics, illustrations, icons, symbols, visual designs, watermarks and other visual materials are protected under applicable law.",
  "Public display does not grant permission to reproduce, modify, or commercially exploit them.",
  "PAGE B  /  DIGITAL CONTENT COPYRIGHT NOTICE",
  "5. AUDIO, VIDEO AND ANIMATIONS",
  "Qualifying original audio recordings, videos, animations, motion graphics, and audiovisual works are protected by copyright law.",
  "Availability on the Website does not grant a licence to reproduce, adapt, or commercially exploit such materials.",
  "6. SOURCE CODE AND SOFTWARE",
  "Original source code, software modules, scripts, and software-related works created or owned by the Company are protected by copyright law.",
  "Third-party and open-source software components remain subject to their respective licences.",
  "7. UI/UX AND VISUAL DESIGN",
  "Original creative expression in user interface design, user experience design, layouts, graphical compositions, visual arrangements, and visual presentation is protected under applicable law.",
  "8. LOGO, BRANDING, ICONS AND WATERMARKS",
  "Original logos, brand identity elements, icons, symbols, watermarks, and creative brand graphics are protected by copyright law, separate from trademark rights.",
  "PAGE A  /  DIGITAL CONTENT COPYRIGHT NOTICE",
  "9. DOCUMENTS AND EDUCATIONAL MATERIALS",
  "Qualifying original PDFs, reports, guides, manuals, presentations, educational resources, and cyber-awareness materials are protected by copyright law.",
  "10. COPYRIGHT NOTICE PRESERVATION",
  "Copyright notices, watermarks, and ownership markings associated with protected materials must be preserved as required by applicable permissions or law.",
  "11. THIRD-PARTY MATERIALS",
  "Third-party materials (Google Fonts, open-source libraries, open-source frameworks, third-party software, licensed media, embedded content) remain subject to their respective owners’ rights and licences.",
  "12. THIRD-PARTY LICENCES",
  "Where third-party material is subject to a separate licence, the terms and conditions of that licence govern permitted uses.",
  "13. NO IMPLIED LICENCE",
  "Website availability does not grant any express or implied licence to reproduce, republish, distribute, modify, or commercially exploit protected materials.",
  "PAGE B  /  DIGITAL CONTENT COPYRIGHT NOTICE",
  "14. PERSONAL VIEWING AND ACCESS",
  "Users may access and personally view public Website content through ordinary lawful use. Personal access does not grant a licence for public reproduction.",
  "15. COPYING AND REPRODUCTION",
  "Protected copyrighted materials should not be reproduced, copied, or republished without applicable legal permission, statutory authorization, or written permission.",
  "16. COMMERCIAL USE",
  "Prior written permission is required for commercial use of protected materials, including paid products, paid services, advertising, marketing, resale, licensing, or commercial integration.",
  "17. MODIFICATION AND ADAPTATION",
  "Prior written permission is required for modification, adaptation, translation, transformation, redesign, rebranding, or creation of derivative works.",
  "18. ATTRIBUTION",
  "Where permission is granted, accurate attribution must be provided. Attribution alone does not replace permission where permission is required.",
  "PAGE A  /  DIGITAL CONTENT COPYRIGHT NOTICE",
  "19. COPYRIGHT PERMISSION",
  "Written permission requests should be submitted to: hr@ibcybersecurity.com.",
  "Permission becomes effective only when expressly granted by the Company in writing.",
  "20. COPYRIGHT INFRINGEMENT",
  "Unauthorized use of protected materials may constitute copyright infringement under applicable law. The Company reserves all legally available remedies.",
  "21. COPYRIGHT INFRINGEMENT REPORTING",
  "Suspected copyright infringement may be reported in writing to: copyrightreport@ibcybersecurity.com.",
  "Reports should contain sufficient detail to allow proper evaluation.",
  "22. STATUTORY EXCEPTIONS AND LIMITATIONS",
  "Nothing in this Notice restricts statutory exceptions, fair dealing, permitted acts, compulsory licences, statutory licences, or lawful defences under Indian law.",
  "23. COPYRIGHT REGISTRATION",
  "Document ID (IBCS-COPYRIGHT-NOTICE-001) is an internal document-control reference separate from government copyright registration certificates.",
  "PAGE B  /  DIGITAL CONTENT COPYRIGHT NOTICE",
  "24. WEBSITE UNDER MAINTENANCE",
  "Temporary website maintenance, redesign, migration, or content revision does not constitute abandonment of copyright in qualifying original works.",
  "25. NO WAIVER OF RIGHTS",
  "Failure to immediately object to an unauthorized use does not constitute consent, permission, licence, assignment, or waiver of copyright protection.",
  "26. SEVERABILITY",
  "If any provision of this Notice is held invalid or unenforceable, remaining provisions shall continue in full force to the extent permitted by law.",
  "27. APPLICABLE LAW",
  "Principally governed by the Copyright Act, 1957 (Sections 13, 14, 17, 18, 19, 30, 30A, 51, 52, 55, 57) and applicable laws of India.",
  "28. GOVERNING LAW AND JURISDICTION",
  "Governed by Indian law. Jurisdiction resides in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "PAGE A  /  DIGITAL CONTENT COPYRIGHT NOTICE",
  "29. OFFICIAL COPYRIGHT NOTICE",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "IB Cyber Security Private Limited reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its qualifying original works.",
  "30. OFFICIAL CONTACT INFORMATION",
  "Permission & Licensing: hr@ibcybersecurity.comInfringement Reports: copyrightreport@ibcybersecurity.comLegal Contact: legaldepartment@ibcybersecurity.com",
  "31. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company)",
  "Official Website: https://ibcybersecurity.com | Email: hr@ibcybersecurity.com | Phone:  | 8093424777",
  "32. DOCUMENT CONTROL",
  "Document Title: Copyright Notice | ID: IBCS-COPYRIGHT-NOTICE-001 | Version: 1.0 | Effective Date & Last Updated: 26 September 2026.",
  "PAGE B  /  DIGITAL CONTENT COPYRIGHT NOTICE",
  "33. FINAL COPYRIGHT NOTICE",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "Qualifying original copyrighted materials appearing on or made available through https://ibcybersecurity.com may be protected under applicable copyright law.",
  "Nothing in this Copyright Notice grants an implied licence or authorizes copying, reproduction, republication, distribution, modification, adaptation or commercial exploitation of protected copyrighted material where such use requires authorization.",
  "Third-party and open-source materials remain subject to their applicable rights and licences.",
  "Nothing in this Copyright Notice restricts any statutory exception, limitation, fair dealing provision, permitted act, compulsory licence, statutory licence, lawful defence or other right that cannot lawfully be restricted under Indian law.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT NOTICE"
];
