export const contentData = [
  "PAGE A  /  WEBSITE COPYRIGHT POLICY",
  "Website Copyright Policy",
  "Coverage of all website content, design, structure and functionality.",
  "1. PURPOSE OF THIS POLICY",
  "This Website Copyright Policy (“Policy”) establishes the copyright framework applicable to the official website of IB Cyber Security Private Limited (“Company”) at https://ibcybersecurity.com (“Website”).",
  "This Policy identifies the copyright rights that the Company lawfully owns or controls, establishes general rules concerning the use of Website content, and explains the relationship between Company-owned materials, third-party materials, licences, permissions and statutory rights.",
  "This Policy shall be interpreted in accordance with applicable laws of India, including the Copyright Act, 1957, as amended from time to time.",
  "2. COPYRIGHT OWNER",
  "Copyright Owner: IB Cyber Security Private Limited | Public / Brand Name: IBCS | Organization Type: Private Limited Company.",
  "The Company reserves all copyright and related rights that it lawfully owns or controls in qualifying original works and materials made available through the Website.",
  "3. WEBSITE COPYRIGHT NOTICE",
  "The standard copyright notice for the Website is: © 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "This notice applies to qualifying original materials owned or lawfully controlled by the Company, subject to applicable law and any applicable third-party rights or licences.",
  "PAGE B  /  WEBSITE COPYRIGHT POLICY",
  "4. SCOPE OF WEBSITE COPYRIGHT",
  "Subject to copyright subsisting in the material and Company ownership/control, protection applies to:",
  "• Website text, articles, publications, educational & cyber-awareness materials, reports, guides, PDFs, documents, & presentations• Images, photographs, graphics, illustrations, audio, video, animations, visual designs, logos, branding, icons, symbols, & watermarks• UI/UX creative expression, source code, software, digital assets, compilations, arrangements, & other literary/artistic/audiovisual/software works",
  "5. LIMITATION OF COPYRIGHT PROTECTION",
  "Copyright protection applies only to material that is legally protectable under law. The Company does not claim exclusive copyright over ideas, facts, methods, procedures, concepts, systems, principles or unprotectable subject matter.",
  "6. WEBSITE CONTENT OWNERSHIP",
  "The Company asserts and reserves copyright lawfully owned or controlled in its original Website content. Agreements, assignments, licences, and Indian law govern ownership determinations.",
  "7. ORIGINAL AND INTERNALLY DEVELOPED CONTENT",
  "Contains original materials created through company-owned or internally managed development. Maintains records including source files, drafts, version histories, design files, repositories, and deployment documentation.",
  "PAGE A  /  WEBSITE COPYRIGHT POLICY",
  "8. OWNERSHIP AND AUTHORSHIP",
  "Copyright ownership and authorship are distinct legal concepts. Identifies IB Cyber Security Private Limited as rights holder only to the extent rights are lawfully owned or controlled, preserving individual author statutory rights.",
  "9. WEBSITE SOURCE CODE",
  "Qualifying original source code and software-related works are protected by copyright. Accessing the Website does not grant a right to copy, modify, adapt, or redistribute code. Third-party and open-source components maintain separate licences.",
  "10. WEBSITE DESIGN AND UI/UX",
  "Interface layout, visual presentation, graphics, illustrations, navigation structure, and design elements are protected where legally protectable and lawfully owned. Functionality or concepts alone do not establish copyright.",
  "11. TEXTUAL CONTENT",
  "Original written articles, descriptions, educational/cyber-awareness content, reports, and guides are protected as qualifying literary works. Unauthorized reproduction or republication constitutes infringement.",
  "PAGE B  /  WEBSITE COPYRIGHT POLICY",
  "12. IMAGES, GRAPHICS AND VISUAL CONTENT",
  "Original images, photographs, graphics, illustrations, icons, symbols, visual designs, and watermarks are protected. Public display does not grant a general reproduction licence.",
  "13. AUDIO, VIDEO AND AUDIOVISUAL CONTENT",
  "Original audio recordings, videos, animations, and motion graphics are protected by copyright. Website availability does not authorize copying, distribution, or commercial exploitation.",
  "14. DOCUMENTS AND DIGITAL PUBLICATIONS",
  "PDFs, reports, guides, manuals, presentations, and educational resources are protected. Availability on the Website does not authorize reproduction, republication, or distribution.",
  "15. LOGOS, BRANDING AND WATERMARKS",
  "Owns or controls copyright in original logos, branding elements, icons, symbols, and watermarks. Copyright protection operates independently of separate trademark or design rights.",
  "PAGE A  /  WEBSITE COPYRIGHT POLICY",
  "16. NO IMPLIED LICENCE",
  "Accessing or viewing the Website does not grant an express or implied licence to reproduce, republish, distribute, modify, adapt, create derivative works, or commercially exploit protected material.",
  "17. PERSONAL VIEWING AND LAWFUL USE",
  "Users may access and personally view publicly available Website content through ordinary lawful Website use. Does not prohibit acts permitted under applicable law.",
  "18. REPRODUCTION OF WEBSITE CONTENT",
  "Reproduction of protected Website content is governed by the Copyright Reproduction Policy. Where reproduction requires authorization, written permission must be obtained.",
  "19. CONTENT PROTECTION",
  "Employs access controls, authentication, copyright notices, watermarks, technical restrictions, security controls, version control, monitoring, and record preservation to protect content.",
  "PAGE B  /  WEBSITE COPYRIGHT POLICY",
  "20. COPYRIGHT MONITORING",
  "Monitors websites, search results, social media, video platforms, online publications, digital repositories, and marketplaces. Similarity detection does not automatically prove infringement.",
  "21. COPYRIGHT RECORDS AND EVIDENCE",
  "Preserves screenshots, URLs, copies, publication info, source files, version histories, metadata, licence records, and correspondence under its Evidence Preservation Policy.",
  "22. THIRD-PARTY MATERIALS",
  "Open-source software, licensed images/fonts, third-party audio/video/graphics, embedded content, and external resources remain subject to their respective owners' rights.",
  "23. THIRD-PARTY AND OPEN-SOURCE LICENCES",
  "Third-party and open-source materials remain subject to their respective licence terms. Nothing in this Policy overrides a valid third-party or open-source licence.",
  "PAGE A  /  WEBSITE COPYRIGHT POLICY",
  "24. EXTERNAL LINKS",
  "Contains links to third-party websites. The Company does not own, control, or endorse third-party content. Users should review applicable terms and privacy policies of third-party portals.",
  "25. COPYRIGHT ATTRIBUTION",
  "Attribution does not, by itself, grant permission to reproduce or use content. Where required, attribution should follow the Company's Copyright Attribution Policy.",
  "26. COPYRIGHT PERMISSION AND LICENSING",
  "Permission or licensing requests should be submitted in writing to: hr@ibcybersecurity.com. Granted permissions specify conditions, scope, duration, territory, and permitted uses.",
  "27. COMMERCIAL USE",
  "Commercial paid products, services, advertising, marketing, commercial publications, training, software, websites, or resale require prior written authorization.",
  "PAGE B  /  WEBSITE COPYRIGHT POLICY",
  "28. MODIFICATION AND ADAPTATION",
  "Modifying, translating, adapting, transforming, or creating derivative works from protected content requires prior written authorization from the Company.",
  "29. REPUBLICATION AND REDISTRIBUTION",
  "Republication or redistribution on external websites, social media, video platforms, documents, apps, or commercial materials requires prior authorization.",
  "30. COPYRIGHT INFRINGEMENT",
  "Unauthorized use of protected Website content constitutes copyright infringement. The Company reserves all statutory rights and legal remedies under law.",
  "31. COPYRIGHT INFRINGEMENT REPORTING",
  "Suspected violations may be reported in writing to: copyrightreport@ibcybersecurity.com including work ID, infringing URL, explanation, evidence, and contact details.",
  "PAGE A  /  WEBSITE COPYRIGHT POLICY",
  "32. TAKEDOWN AND REMOVAL REQUESTS",
  "Requests removal or disabling of access through relevant websites, platforms, hosting providers, or search engines in accordance with applicable law and platform procedures.",
  "33. AVAILABLE LEGAL REMEDIES",
  "Pursues cessation of use, removal, cease-and-desist communications, platform complaints, civil lawsuits, and criminal proceedings under law for established infringement.",
  "34. NO AUTOMATIC DETERMINATION OF INFRINGEMENT",
  "A copyright notice, content match, similarity, screenshot, or allegation does not automatically establish infringement. Assessment depends on law, authorization, fair dealing, and facts.",
  "35. STATUTORY EXCEPTIONS AND LIMITATIONS",
  "Nothing restricts fair dealing, statutory exceptions, permitted acts, compulsory licences, statutory licences, or lawful defences under Indian copyright law.",
  "PAGE B  /  WEBSITE COPYRIGHT POLICY",
  "36. NO WAIVER OF RIGHTS",
  "Failure to immediately object to or act against a particular use does not constitute consent, authorization, waiver, ownership transfer, or abandonment of rights.",
  "37. COPYRIGHT REGISTRATION",
  "Policy & Document ID (IBCS-WEBSITE-COPYRIGHT-POLICY-001) are internal document control references, separate from government registration certificates.",
  "38. RELATIONSHIP WITH OTHER COPYRIGHT POLICIES",
  "Read together with Notice, Disclaimer, Permission, Licensing, Attribution, Reproduction, Content Protection, Enforcement, and Preservation policies. Applicable law prevails in case of conflict.",
  "39. APPLICABLE INDIAN LAW",
  "Interpreted under Indian law, principally the Copyright Act, 1957 (Sections 13, 14, 17, 18, 19, 30, 30A, 51, 52, 55, 57). Mandatory statutory law prevails.",
  "PAGE A  /  WEBSITE COPYRIGHT POLICY",
  "40. GOVERNING LAW AND JURISDICTION",
  "Governed by Indian law. Jurisdiction resides in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "41. SEVERABILITY",
  "If any provision is determined invalid, remaining provisions continue in effect to the maximum extent legally permissible under law.",
  "42. POLICY INTERPRETATION",
  "Interpreted consistently with applicable Indian law. Mandatory statutory legal provisions prevail over conflicting Policy terms.",
  "PAGE B  /  WEBSITE COPYRIGHT POLICY",
  "43. OFFICIAL COPYRIGHT INFORMATION",
  "Copyright Owner: IB Cyber Security Private Limited | Public / Brand Name: IBCS | Private Limited Company | Official Website: https://ibcybersecurity.com",
  "44. OFFICIAL CONTACT INFORMATION",
  "Permissions & Licensing: hr@ibcybersecurity.com | Infringement Reports: copyrightreport@ibcybersecurity.com | Legal Contact: legaldepartment@ibcybersecurity.com",
  "45. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited | Public / Brand Name: IBCS | Private Limited Company",
  "Official Website: https://ibcybersecurity.com | Email: hr@ibcybersecurity.com | Legal: legaldepartment@ibcybersecurity.com | Infringements: copyrightreport@ibcybersecurity.com | Phone:  | 8093424777",
  "PAGE A  /  WEBSITE COPYRIGHT POLICY",
  "46. DOCUMENT CONTROL",
  "Document Title: Website Copyright Policy | Document ID: IBCS-WEBSITE-COPYRIGHT-POLICY-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.",
  "Copyright Owner: IB Cyber Security Private Limited | Public / Brand Name: IBCS | Official Website: https://ibcybersecurity.com",
  "PAGE B  /  WEBSITE COPYRIGHT POLICY",
  "47. FINAL WEBSITE COPYRIGHT DECLARATION",
  "IB Cyber Security Private Limited reserves all copyright and related rights that it lawfully owns or controls in qualifying original Website content and materials made available through https://ibcybersecurity.com.",
  "Public access to the Website does not, by itself, transfer ownership or grant a general licence to reproduce, republish, distribute, modify, adapt or commercially exploit protected Company-owned content where such use is restricted by applicable law.",
  "Third-party materials remain subject to their respective owners' rights and applicable licences.",
  "The Company may use reasonable measures to identify, protect, monitor and preserve evidence concerning unauthorized use of qualifying Company-owned content.",
  "Nothing in this Policy restricts any statutory exception, limitation, fair dealing provision, permitted act, compulsory licence, statutory licence, lawful defence or other right that cannot lawfully be restricted under Indian law.",
  "All copyright and related rights lawfully owned or controlled by IB Cyber Security Private Limited are reserved.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF WEBSITE COPYRIGHT POLICY"
];
