export const contentData = [
  "PAGE A  /  COPYRIGHT USAGE POLICY",
  "Copyright Usage Policy",
  "Guidelines for lawful and permitted use of our content.",
  "1. PURPOSE OF THIS COPYRIGHT USAGE POLICY",
  "This Copyright Usage Policy (“Policy”) establishes the rules governing the use of qualifying original copyrighted works and materials owned or lawfully controlled by IB Cyber Security Private Limited (“Company”) and made available through or in connection with its official Website at https://ibcybersecurity.com (“Website”).",
  "The purpose of this Policy is to clearly identify permitted and restricted uses of the Company’s original copyrighted materials and to establish a transparent process for obtaining permission where permission is required.",
  "This Policy shall be interpreted together with the Copyright Act, 1957, as amended from time to time, other applicable laws of India, valid third-party rights, applicable licences and statutory exceptions and limitations.",
  "2. COPYRIGHT OWNER",
  "The copyright owner identified under this Policy is: IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company).",
  "The Company reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its qualifying original works and materials.",
  "3. MATERIALS COVERED BY THIS POLICY",
  "Applies to website text, written content, articles, publications, educational & cyber-awareness materials, original images, audio, video, animations, graphics, illustrations, icons, symbols, watermark designs, branding materials, UI/UX creative expression, visual designs, source code, software, PDFs, documents, presentations, digital assets, compilations, and arrangements.",
  "PAGE B  /  COPYRIGHT USAGE POLICY",
  "4. GENERAL RULE OF USE & 5. PERMITTED PERSONAL VIEWING",
  "Users may access and view publicly available Website content for legitimate personal, informational, and non-commercial purposes. Permitted viewing does not transfer copyright ownership or grant an automatic licence to reproduce, modify, distribute, or commercially exploit protected materials.",
  "6. PERMITTED URL SHARING & 7. CONTENT COPYING RESTRICTIONS",
  "Users may share official Website URLs and link to https://ibcybersecurity.com provided links do not imply false endorsement or create an unauthorized mirror. Copying, reproducing, or republishing protected original content is prohibited without authorization.",
  "8. SOCIAL MEDIA SHARING & REPOSTING",
  "Written permission is required before reposting materials on social media (unless native sharing applies). Reposts require: proper credit, no material alterations, staying within scope, and no false endorsement.",
  "9. NATIVE SOCIAL-MEDIA SHARING",
  "Native social-media sharing functionality provided by platforms may be used subject to platform terms, but does not grant permission to download or redistribute underlying works.",
  "PAGE A  /  COPYRIGHT USAGE POLICY",
  "10. SCREENSHOTS AND SCREEN RECORDINGS",
  "Screenshots and recordings containing protected materials may constitute restricted reproduction. Written permission is required before public publication or commercial distribution.",
  "11. EDUCATIONAL QUOTATION AND LIMITED USE",
  "Limited quotation is permitted under statutory exceptions. Users must use necessary amounts, provide accurate attribution, identify the source, and avoid presenting material as their own.",
  "12. ATTRIBUTION REQUIREMENTS",
  "Where permission is granted, attribution should specify: IB Cyber Security Private Limited | IBCS | Official Website: https://ibcybersecurity.com.",
  "13. COMMERCIAL USE RESTRICTION",
  "Commercial use of protected materials (selling, paid integration, advertising, promotional campaigns, paid services, licensing) is strictly prohibited without prior written authorization.",
  "PAGE B  /  COPYRIGHT USAGE POLICY",
  "14. MODIFICATION AND ADAPTATION RESTRICTION",
  "Users must not edit, rebrand, redesign, translate, transform, or create derivative works from protected Company materials without prior written authorization.",
  "15. DOWNLOADING POLICY & 16. REDISTRIBUTION RESTRICTIONS",
  "Website downloads do not grant unrestricted reuse or redistribution rights. Uploading to another website, publishing on external platforms, or creating unauthorized collections is prohibited.",
  "17. SOURCE CODE & 18. VISUAL MATERIALS",
  "Copying, modifying, or commercially exploiting protected Company source code, scripts, images, graphics, illustrations, icons, symbols, or watermarks requires written permission.",
  "19. AUDIO/VIDEO & 20. DOCUMENTS/PDFs",
  "Protected audio, video, animations, reports, manuals, PDFs, and educational digital documents must not be reproduced, modified, or redistributed without authorization.",
  "PAGE A  /  COPYRIGHT USAGE POLICY",
  "21. WATERMARKS & 22. THIRD-PARTY MATERIALS",
  "Copyright notices and watermarks must not be removed or altered. Third-party materials (Google Fonts, open-source libraries) remain subject to their respective owners' licence terms.",
  "23. NO IMPLIED LICENCE",
  "Public accessibility or website viewing does not create an implied licence to reproduce, modify, distribute, publish, adapt or commercially exploit protected works.",
  "24. WRITTEN PERMISSION REQUESTS",
  "Where permission is required, requests must be submitted in writing to: hr@ibcybersecurity.com specifying requester details, material ID/URL, proposed use, medium, purpose, duration, and audience.",
  "25. PERMISSION TERMS & 26. NO TRANSFER OF COPYRIGHT",
  "Granted permission applies only to specific stated terms, platform, and duration. Permission does not transfer copyright ownership unless a valid written assignment provides otherwise.",
  "PAGE B  /  COPYRIGHT USAGE POLICY",
  "27. STATUTORY EXCEPTIONS & 28. FAIR DEALING",
  "Uses falling within statutory exceptions under Indian copyright law remain permitted subject to legal conditions. Uses outside statutory exceptions remain subject to Company copyright.",
  "29. COPYRIGHT INFRINGEMENT & 30. REPORTING",
  "Unauthorized reproduction, publication, distribution, or commercial exploitation constitutes infringement. Reports should be sent to: copyrightreport@ibcybersecurity.com.",
  "31. ENFORCEMENT ACTIONS & 32. MAINTENANCE",
  "The Company reserves all civil remedies, legal notices, cease-and-desist communications, and statutory remedies. Site updates or maintenance do not constitute abandonment of copyright.",
  "33. INTERPRETATION, 34. LAW & 35. JURISDICTION",
  "Governed by the Copyright Act, 1957 (Sections 13, 14, 17, 51, 52, 55). Legal matters reside in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "PAGE A  /  COPYRIGHT USAGE POLICY",
  "36. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited (Brand: IBCS | Private Limited Company)",
  "Emails: hr@ibcybersecurity.com | legaldepartment@ibcybersecurity.com | copyrightreport@ibcybersecurity.com | Phone:  | 8093424777",
  "37. DOCUMENT CONTROL & 38. COPYRIGHT STATEMENT",
  "Document Title: Copyright Usage Policy | ID: IBCS-COPYRIGHT-USAGE-POLICY-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "PAGE B  /  COPYRIGHT USAGE POLICY",
  "39. FINAL USAGE DECLARATION",
  "IB Cyber Security Private Limited permits public access and viewing of its Website subject to this Copyright Usage Policy.",
  "Users may share official Website URLs and use materials only as expressly permitted by this Policy, written authorization, or Indian law.",
  "Except where permitted by law, unauthorized copying, reproduction, distribution, modification, adaptation, or commercial exploitation is prohibited.",
  "Third-party materials remain subject to their respective owners’ rights.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT USAGE POLICY"
];
