export const contentData = [
  "PAGE A  /  COPYRIGHT PERMISSION POLICY",
  "Copyright Permission Policy",
  "How to request permission for using our content legally.",
  "1. PURPOSE OF THIS PERMISSION POLICY",
  "This Copyright Permission Policy (“Policy”) establishes the procedure and conditions for requesting and obtaining written permission to use qualifying original copyrighted works owned or lawfully controlled by IB Cyber Security Private Limited (“Company”) and made available through or in connection with its official Website at https://ibcybersecurity.com (“Website”).",
  "The purpose of this Policy is to provide a clear and transparent process for individuals, organizations, educational institutions, businesses and other parties seeking permission to reproduce, publish, distribute, adapt, modify, communicate, display or otherwise use protected Company-owned materials.",
  "This Policy shall be interpreted in accordance with the Copyright Act, 1957, as amended from time to time, other applicable laws of India, applicable licences, third-party rights and statutory exceptions and limitations.",
  "2. COPYRIGHT OWNER & 3. MATERIALS SUBJECT TO PERMISSION",
  "Owner: IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company).",
  "Applies to website text, written content, articles, publications, educational & cyber-awareness materials, original images, audio, video, animations, graphics, illustrations, icons, symbols, watermark designs, branding materials, UI/UX creative expression, visual designs, source code, software, PDFs, documents, presentations, digital assets, compilations, and arrangements.",
  "PAGE B  /  COPYRIGHT PERMISSION POLICY",
  "4. WHEN WRITTEN PERMISSION IS REQUIRED",
  "Unless expressly permitted by law or this Policy, written permission is required for: reproduction, republishing, redistribution, commercial use, public display, social-media reposting, modification, adaptation, translation, derivative works, or paid services.",
  "5. PERMITTED USES WITHOUT INDIVIDUAL PERMISSION",
  "Permitted without individual permission: personal viewing, legitimate informational access, sharing URL (https://ibcybersecurity.com), linking to official Website, and native social-media sharing.",
  "6. URL SHARING & 7. SOCIAL-MEDIA REPOSTING",
  "Users may share links directly to https://ibcybersecurity.com provided links do not imply false endorsement. Social-media reposts require written permission (unless native platform sharing applies) and proper attribution.",
  "8. SCREENSHOTS & 9. EDUCATIONAL QUOTATION",
  "Publicly publishing screenshots containing protected materials requires written permission. Limited educational quotation is permitted under statutory fair dealing subject to accurate attribution.",
  "PAGE A  /  COPYRIGHT PERMISSION POLICY",
  "10. COMMERCIAL USE & 11. MODIFICATION RESTRICTIONS",
  "Commercial use (paid products, advertising, commercial campaigns, paid publications, resale, licensing) requires prior written permission. Editing, rebranding, redesigning, translating, or creating derivative works is prohibited without written permission.",
  "12. DOWNLOADING & 13. SOURCE CODE USAGE",
  "Website availability does not grant unrestricted download or redistribution rights. Protected source code, scripts, and software modules require prior written permission.",
  "14. IMAGES/GRAPHICS & 15. AUDIO/VIDEO/ANIMATION",
  "Reproducing, modifying, redistributing, or commercially exploiting protected images, photographs, graphics, illustrations, icons, symbols, watermarks, audio, voice recordings, videos, or animations requires prior written permission.",
  "16. DOCUMENTS, PDFs & EDUCATIONAL ASSETS",
  "Prior written permission is required for reproducing, redistributing, or modifying protected PDFs, reports, guides, manuals, presentations, or educational digital documents.",
  "PAGE B  /  COPYRIGHT PERMISSION POLICY",
  "17. ATTRIBUTION REQUIREMENTS",
  "Where permission is granted, attribution should specify: IB Cyber Security Private Limited | IBCS | Official Website: https://ibcybersecurity.com.",
  "18. PERMISSION REQUEST METHOD",
  "All permission requests must be submitted in writing to: hr@ibcybersecurity.com before proposed use begins. Email requests become effective only when expressly granted in writing.",
  "19. REQUIRED INFORMATION FOR REQUESTS",
  "Requests should include: requester name & company, contact email & phone, work ID & URL, proposed use description, exact portion, purpose (commercial/non-commercial), medium, audience, duration, territory, attribution, and proposed modifications.",
  "20. REVIEW & 21. APPROVAL PROCESS",
  "The Company evaluates work nature, ownership, purpose, commercial status, material amount, audience, platform, duration, and potential impact. Submissions do not guarantee approval.",
  "PAGE A  /  COPYRIGHT PERMISSION POLICY",
  "22. SCOPE OF GRANTED PERMISSION",
  "Permission applies only to the specific work, material, use, purpose, platform, duration, territory, audience, modification, and distribution method identified in writing.",
  "23. NO IMPLIED PERMISSION",
  "Silence, failure to respond, website accessibility, public availability, prior access, downloading, viewing, URL sharing, or unobjected previous use do NOT constitute permission.",
  "24. NO TRANSFER OF COPYRIGHT OWNERSHIP",
  "Permission or licence to use a work does not transfer copyright ownership. Copyright remains with IB Cyber Security Private Limited unless transferred by a valid legal instrument.",
  "25. LICENCE TERMS & 26. NON-TRANSFERABILITY",
  "Licences specify permitted rights, duration, territory, platform, attribution, sublicensing rules, fees, and termination conditions. Permissions are personal and non-transferable.",
  "PAGE B  /  COPYRIGHT PERMISSION POLICY",
  "27. MODIFICATION SCOPE & 28. COMMERCIAL PERMISSION",
  "Permission without express modification rights does not authorize editing or adaptations. Commercial authorizations specify scope, duration, territory, attribution, royalties, and termination.",
  "29. ROYALTIES OR FEES & 30. FUTURE USES",
  "The Company may require a fee or royalty for commercial licences. Permission for one use does not authorize future, additional, or materially different uses.",
  "31. TERMINATION & 32. THIRD-PARTY ASSETS",
  "The Company reserves withdrawal rights according to terms and law. Excludes third-party fonts (Google Fonts) and open-source software (licences must be obtained directly from third-party owners).",
  "33. STATUTORY EXCEPTIONS & 34. COMPULSORY LICENCES",
  "Nothing restricts statutory exceptions, fair dealing, or compulsory/statutory licensing under the Copyright Act, 1957.",
  "PAGE A  /  COPYRIGHT PERMISSION POLICY",
  "35. WRITTEN LICENSING & 36. REGISTRATION",
  "Licences must be documented in writing. Document ID (IBCS-COPYRIGHT-PERMISSION-POLICY-001) is an internal control reference separate from government registration.",
  "37. INFRINGEMENT & 38. REPORTING",
  "Use without required permission constitutes copyright infringement under Indian law. Suspected violations may be reported to: copyrightreport@ibcybersecurity.com.",
  "39. MAINTENANCE & 40. INTERPRETATION",
  "Temporary website maintenance does not affect previously granted written permissions. Policy is interpreted consistently with Indian copyright law.",
  "41. APPLICABLE INDIAN LAW & 42. JURISDICTION",
  "Governed by the Copyright Act, 1957 (Sections 13, 14, 17, 18, 19, 30, 30A, 51, 52). Legal matters reside in competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "PAGE B  /  COPYRIGHT PERMISSION POLICY",
  "43. OFFICIAL PERMISSION CONTACT",
  "Permission Requests: hr@ibcybersecurity.comInfringement Reports: copyrightreport@ibcybersecurity.comLegal Contact: legaldepartment@ibcybersecurity.com",
  "44. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company)Official Website: https://ibcybersecurity.com | Phone:  | 8093424777",
  "45. DOCUMENT CONTROL & 46. COPYRIGHT STATEMENT",
  "Document Title: Copyright Permission Policy | ID: IBCS-COPYRIGHT-PERMISSION-POLICY-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.© 2026 IB Cyber Security Private Limited. All Rights Reserved.",
  "PAGE A  /  COPYRIGHT PERMISSION POLICY",
  "47. FINAL PERMISSION DECLARATION",
  "IB Cyber Security Private Limited may grant written permission or copyright licences for the use of qualifying original works that it lawfully owns or controls.",
  "Any permission granted by the Company shall be limited to the rights, material, purpose, scope, duration, platform, territory and other conditions expressly stated in the written authorization or licence.",
  "No person or organization shall acquire broader rights merely because a permission request has been submitted, a Website material is publicly accessible, or the Company has previously permitted a different use.",
  "Nothing in this Policy restricts any statutory exception, limitation, compulsory licence, statutory licence or other right that cannot lawfully be restricted under applicable Indian law.",
  "All copyright and related rights lawfully owned or controlled by IB Cyber Security Private Limited are reserved.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT PERMISSION POLICY"
];
