/**
 * Copyright Policies & Intellectual Property Data Source
 * Contains all 16 standardized copyright framework definitions and emblem configuration.
 */

export const COPYRIGHT_LETTERS = [
  { char: 'C', x: 15 },
  { char: 'O', x: 62 },
  { char: 'P', x: 112 },
  { char: 'Y', x: 156 },
  { char: 'R', x: 202 },
  { char: 'I', x: 250 },
  { char: 'G', x: 274 },
  { char: 'H', x: 324 },
  { char: 'T', x: 374 },
];

export const COPYRIGHT_CARDS = [
  {
    id: 1,
    number: '01',
    name: 'Copyright Legal Notice',
    title: 'COPYRIGHT',
    subtitle: 'LEGAL NOTICE',
    badge: 'STATUTORY COMPLIANCE',
    category: 'Notices',
    code: 'CR-01',
    color: '#d97706',
    ringStart: '#2563eb',
    ringMid: '#1e3a8a',
    ringEnd: '#0f172a',
    cStart: '#3b82f6',
    cEnd: '#1d4ed8',
    accentLine: '#60a5fa',
    capsuleBg: '#0f172a',
  },
  {
    id: 2,
    number: '02',
    name: 'Copyright Declaration',
    title: 'COPYRIGHT',
    subtitle: 'DECLARATION',
    badge: 'FORMAL STATEMENT',
    category: 'Ownership',
    code: 'CR-02',
    color: '#059669',
    ringStart: '#059669',
    ringMid: '#065f46',
    ringEnd: '#022c22',
    cStart: '#10b981',
    cEnd: '#047857',
    accentLine: '#34d399',
    capsuleBg: '#022c22',
  },
  {
    id: 3,
    number: '03',
    name: 'Copyright Ownership Statement',
    title: 'COPYRIGHT',
    subtitle: 'OWNERSHIP STATEMENT',
    badge: 'PROPRIETARY IP',
    category: 'Ownership',
    code: 'CR-03',
    color: '#7c3aed',
    ringStart: '#7c3aed',
    ringMid: '#4c1d95',
    ringEnd: '#1e1b4b',
    cStart: '#8b5cf6',
    cEnd: '#6d28d9',
    accentLine: '#a78bfa',
    capsuleBg: '#1e1b4b',
  },
  {
    id: 4,
    number: '04',
    name: 'Copyright Protection Notice',
    title: 'COPYRIGHT',
    subtitle: 'PROTECTION NOTICE',
    badge: 'ALL RIGHTS RESERVED',
    category: 'Notices',
    code: 'CR-04',
    color: '#0284c7',
    ringStart: '#0284c7',
    ringMid: '#0369a1',
    ringEnd: '#0c4a6e',
    cStart: '#38bdf8',
    cEnd: '#0284c7',
    accentLine: '#7dd3fc',
    capsuleBg: '#082f49',
  },
  {
    id: 5,
    number: '05',
    name: 'Copyright Infringement Notice',
    title: 'COPYRIGHT',
    subtitle: 'INFRINGEMENT NOTICE',
    badge: 'DMCA ENFORCEMENT',
    category: 'Enforcement',
    code: 'CR-05',
    color: '#dc2626',
    ringStart: '#dc2626',
    ringMid: '#991b1b',
    ringEnd: '#450a0a',
    cStart: '#ef4444',
    cEnd: '#b91c1c',
    accentLine: '#fca5a5',
    capsuleBg: '#450a0a',
  },
  {
    id: 6,
    number: '06',
    name: 'Copyright Usage Policy',
    title: 'COPYRIGHT',
    subtitle: 'USAGE POLICY',
    badge: 'TERMS OF USE',
    category: 'Policies',
    code: 'CR-06',
    color: '#ea580c',
    ringStart: '#ea580c',
    ringMid: '#9a3412',
    ringEnd: '#431407',
    cStart: '#f97316',
    cEnd: '#c2410c',
    accentLine: '#fdba74',
    capsuleBg: '#431407',
  },
  {
    id: 7,
    number: '07',
    name: 'Copyright Reproduction Policy',
    title: 'COPYRIGHT',
    subtitle: 'REPRODUCTION POLICY',
    badge: 'DISTRIBUTION',
    category: 'Policies',
    code: 'CR-07',
    color: '#0d9488',
    ringStart: '#0d9488',
    ringMid: '#115e59',
    ringEnd: '#042f2e',
    cStart: '#14b8a6',
    cEnd: '#0f766e',
    accentLine: '#5eead4',
    capsuleBg: '#042f2e',
  },
  {
    id: 8,
    number: '08',
    name: 'Copyright Permission Policy',
    title: 'COPYRIGHT',
    subtitle: 'PERMISSION POLICY',
    badge: 'AUTHORIZATION',
    category: 'Policies',
    code: 'CR-08',
    color: '#4f46e5',
    ringStart: '#4f46e5',
    ringMid: '#3730a3',
    ringEnd: '#1e1b4b',
    cStart: '#6366f1',
    cEnd: '#4338ca',
    accentLine: '#a5b4fc',
    capsuleBg: '#1e1b4b',
  },
  {
    id: 9,
    number: '09',
    name: 'Copyright Content Protection Policy',
    title: 'COPYRIGHT',
    subtitle: 'CONTENT PROTECTION',
    badge: 'ASSET SECURITY',
    category: 'Notices',
    code: 'CR-09',
    color: '#b45309',
    ringStart: '#f59e0b',
    ringMid: '#b45309',
    ringEnd: '#78350f',
    cStart: '#fbbf24',
    cEnd: '#d97706',
    accentLine: '#fef08a',
    capsuleBg: '#451a03',
  },
  {
    id: 10,
    number: '10',
    name: 'Website Copyright Policy',
    title: 'COPYRIGHT',
    subtitle: 'WEBSITE POLICY',
    badge: 'DIGITAL DOMAIN',
    category: 'Policies',
    code: 'CR-10',
    color: '#2563eb',
    ringStart: '#2563eb',
    ringMid: '#1e40af',
    ringEnd: '#172554',
    cStart: '#3b82f6',
    cEnd: '#1d4ed8',
    accentLine: '#93c5fd',
    capsuleBg: '#172554',
  },
  {
    id: 11,
    number: '11',
    name: 'Digital Content Copyright Notice',
    title: 'COPYRIGHT',
    subtitle: 'DIGITAL CONTENT NOTICE',
    badge: 'MEDIA RIGHTS',
    category: 'Notices',
    code: 'CR-11',
    color: '#0891b2',
    ringStart: '#0891b2',
    ringMid: '#0e7490',
    ringEnd: '#164e63',
    cStart: '#06b6d4',
    cEnd: '#0891b2',
    accentLine: '#67e8f9',
    capsuleBg: '#164e63',
  },
  {
    id: 12,
    number: '12',
    name: 'Copyright Enforcement Policy',
    title: 'COPYRIGHT',
    subtitle: 'ENFORCEMENT POLICY',
    badge: 'LEGAL ACTION',
    category: 'Enforcement',
    code: 'CR-12',
    color: '#e11d48',
    ringStart: '#e11d48',
    ringMid: '#881337',
    ringEnd: '#4c0519',
    cStart: '#f43f5e',
    cEnd: '#be123c',
    accentLine: '#fda4af',
    capsuleBg: '#4c0519',
  },
  {
    id: 13,
    number: '13',
    name: 'Copyright Legal Disclaimer',
    title: 'COPYRIGHT',
    subtitle: 'LEGAL DISCLAIMER',
    badge: 'LIABILITY CLAUSE',
    category: 'Enforcement',
    code: 'CR-13',
    color: '#334155',
    ringStart: '#334155',
    ringMid: '#1e293b',
    ringEnd: '#0f172a',
    cStart: '#64748b',
    cEnd: '#334155',
    accentLine: '#cbd5e1',
    capsuleBg: '#0f172a',
  },
  {
    id: 14,
    number: '14',
    name: 'Copyright Registration & Certificate',
    title: 'COPYRIGHT',
    subtitle: 'REGISTRATION & CERT.',
    badge: 'OFFICIAL RECORD',
    category: 'Ownership',
    code: 'CR-14',
    color: '#d97706',
    ringStart: '#d97706',
    ringMid: '#b45309',
    ringEnd: '#78350f',
    cStart: '#f59e0b',
    cEnd: '#d97706',
    accentLine: '#fef08a',
    capsuleBg: '#451a03',
  },
  {
    id: 15,
    number: '15',
    name: 'Copyright Licensing Policy',
    title: 'COPYRIGHT',
    subtitle: 'LICENSING POLICY',
    badge: 'COMMERCIAL TERMS',
    category: 'Licensing',
    code: 'CR-15',
    color: '#6d28d9',
    ringStart: '#7c3aed',
    ringMid: '#5b21b6',
    ringEnd: '#2e1065',
    cStart: '#8b5cf6',
    cEnd: '#6d28d9',
    accentLine: '#c4b5fd',
    capsuleBg: '#2e1065',
  },
  {
    id: 16,
    number: '16',
    name: 'Copyright Attribution Policy',
    title: 'COPYRIGHT',
    subtitle: 'ATTRIBUTION POLICY',
    badge: 'CREDIT & AUTHOR',
    category: 'Policies',
    code: 'CR-16',
    color: '#059669',
    ringStart: '#059669',
    ringMid: '#065f46',
    ringEnd: '#022c22',
    cStart: '#10b981',
    cEnd: '#047857',
    accentLine: '#6ee7b7',
    capsuleBg: '#022c22',
  },
];

export function getTwoLineName(name) {
  const customSplits = {
    'Copyright Legal Notice': ['COPYRIGHT', 'LEGAL NOTICE'],
    'Copyright Declaration': ['COPYRIGHT', 'DECLARATION'],
    'Copyright Ownership Statement': ['COPYRIGHT', 'OWNERSHIP STATEMENT'],
    'Copyright Protection Notice': ['COPYRIGHT', 'PROTECTION NOTICE'],
    'Copyright Infringement Notice': ['COPYRIGHT', 'INFRINGEMENT NOTICE'],
    'Copyright Usage Policy': ['COPYRIGHT', 'USAGE POLICY'],
    'Copyright Reproduction Policy': ['COPYRIGHT', 'REPRODUCTION POLICY'],
    'Copyright Permission Policy': ['COPYRIGHT', 'PERMISSION POLICY'],
    'Copyright Content Protection Policy': ['COPYRIGHT CONTENT', 'PROTECTION POLICY'],
    'Website Copyright Policy': ['WEBSITE', 'COPYRIGHT POLICY'],
    'Digital Content Copyright Notice': ['DIGITAL CONTENT', 'COPYRIGHT NOTICE'],
    'Copyright Enforcement Policy': ['COPYRIGHT', 'ENFORCEMENT POLICY'],
    'Copyright Legal Disclaimer': ['COPYRIGHT', 'LEGAL DISCLAIMER'],
    'Copyright Registration & Certificate': ['COPYRIGHT', 'REGISTRATION & CERTIFICATE'],
    'Copyright Licensing Policy': ['COPYRIGHT', 'LICENSING POLICY'],
    'Copyright Attribution Policy': ['COPYRIGHT', 'ATTRIBUTION POLICY'],
  };

  if (customSplits[name]) {
    return customSplits[name];
  }

  const words = (name || '').split(' ');
  if (words.length <= 1) return [(name || '').toUpperCase(), ''];
  const mid = Math.ceil(words.length / 2);
  return [
    words.slice(0, mid).join(' ').toUpperCase(),
    words.slice(mid).join(' ').toUpperCase(),
  ];
}

