export const SKILLS_DATA = [
  { id: 1, title: "Software Development Training" },
  { id: 2, title: "Software Development Internship" },
  { id: 3, title: "Information Technology Training" },
  { id: 4, title: "Information Technology Internship" },
  { id: 5, title: "Cybersecurity Training" },
  { id: 6, title: "Cybersecurity Internship" },
  { id: 7, title: "Cyber Crime Investigation Training" },
  { id: 8, title: "Cyber Crime Investigation Internship" },
  { id: 9, title: "Digital Forensics Training" },
  { id: 10, title: "Digital Forensics Internship" },
  { id: 11, title: "Cyber Threat Intelligence Training" },
  { id: 12, title: "Cyber Threat Intelligence Internship" },
  { id: 13, title: "Artificial Intelligence & Machine Learning Training" },
  { id: 14, title: "Artificial Intelligence & Machine Learning Internship" },
  { id: 15, title: "Data Science & Analytics Training" },
  { id: 16, title: "Data Science & Analytics Internship" },
  { id: 17, title: "Web Development Training" },
  { id: 18, title: "Web Development Internship" },
  { id: 19, title: "Mobile Application Development Training" },
  { id: 20, title: "Mobile Application Development Internship" },
  { id: 21, title: "Cloud Computing & DevOps Training" },
  { id: 22, title: "Cloud Computing & DevOps Internship" },
  { id: 23, title: "Networking & Infrastructure Training" },
  { id: 24, title: "Networking & Infrastructure Internship" },
  { id: 25, title: "Cyber Law & Digital Compliance Training" },
  { id: 26, title: "Cyber Law & Digital Compliance Internship" },
  { id: 27, title: "Cyber Awareness & Digital Safety Training" },
  { id: 28, title: "Cyber Awareness & Digital Safety Internship" },
  { id: 29, title: "Professional Training Programs" },
  { id: 30, title: "Professional Internship Programs" },
  { id: 31, title: "Workshops & Practical Learning Programs" },
  { id: 32, title: "Career Development & Placement Programs" }
];
