export const contentData = [
  "PAGE A  /  COPYRIGHT LEGAL NOTICE",
  "Copyright Legal Notice",
  "1. PURPOSE AND SCOPE OF THIS NOTICE",
  "This Copyright Legal Notice (“Notice”) applies to the official website of IB Cyber Security Private Limited, a legally registered Private Limited Company operating under the public and brand name IBCS, accessible at https://ibcybersecurity.com (the “Website”).",
  "The purpose of this Notice is to provide clear and formal notice regarding the copyright and related intellectual-property rights applicable to the original works and materials owned or lawfully controlled by IB Cyber Security Private Limited (the “Company”) and made available through the Website.",
  "The Company respects the intellectual-property rights of third parties and expects all visitors, users, organizations and other persons accessing or using the Website (“Users”) to respect the Company’s lawful rights in its original materials.",
  "2. COPYRIGHT OWNERSHIP",
  "2.1 Copyright Owner: IB Cyber Security Private Limited is the copyright owner of original works in which the Company holds copyright, subject to applicable law, contractual arrangements, valid assignments, licences and other legally recognized rights.",
  "2.2 Ownership of Original Materials: All original materials created by, developed by, commissioned by, acquired by, assigned to, or otherwise lawfully owned or controlled by the Company are claimed and protected under applicable law.",
  "3. LEGAL BASIS FOR COPYRIGHT PROTECTION",
  "Copyright matters relating to qualifying materials associated with the Website are principally governed by the Copyright Act, 1957, as amended from time to time, together with other applicable laws of India.",
  "This Notice refers particularly to: Section 13 (works in which copyright may subsist), Section 14 (meaning and scope of copyright), Section 17 (first ownership), Section 51 (infringing conditions), Section 52 (fair dealing acts), and Section 55 (civil remedies).",
  "4. SCOPE OF COPYRIGHT PROTECTION",
  "4.1 Original Website Content: Includes original written content, articles, publications, educational guides, reports, compilations, and structured content. Facts, ideas, or concepts are not claimed under copyright.",
  "4.2 Website Design and Creative Materials: Includes UI/UX design, visual design layout compositions, illustrations, graphic designs, animations, icons, and interactive visual elements.",
  "PAGE B  /  COPYRIGHT LEGAL NOTICE",
  "4.3 Source Code and Software",
  "Where owned or lawfully controlled by the Company, copyright applies to software-related materials, source code, scripts, website modules, implementations, technical documentation, and database structures.",
  "4.4 Images, Videos & Multimedia",
  "Original multimedia works include photographs, videos, audio materials, animations, presentations, digital publications, PDFs, and educational resources.",
  "5. ORIGINAL MATERIALS COVERED BY THIS NOTICE",
  "Includes website text, educational files, graphics, branding logo materials owned by the Company, source code, database structures, and digital assets.",
  "6. THIRD-PARTY MATERIALS",
  "6.1 Third-Party Exclusions: Third-party materials (such as Google Fonts, open-source libraries) remain subject to their respective owners' terms and are not claimed by the Company.",
  "6.2 Third-Party Rights: Users must comply with applicable licence terms governing third-party materials.",
  "PAGE C  /  COPYRIGHT LEGAL NOTICE",
  "7. WEBSITE ACCESS AND PERMITTED USE",
  "Users may access and view publicly available portions of the Website for legitimate personal or informational purposes. Access does not transfer copyright ownership.",
  "8. RESTRICTIONS ON USE OF COPYRIGHTED MATERIALS",
  "Except where authorized, Users must not reproduce, copy, modify, distribute, commercially exploit, sell, scrape, or republish the Company's original materials.",
  "9. PERSONAL AND NON-COMMERCIAL USE",
  "Personal viewing is permitted. However, personal access does not grant a right to copy, modify, distribute, or commercially exploit protected materials without written authorization.",
  "10. SOCIAL MEDIA REPOSTING",
  "Original materials must not be reproduced on social media without permission, except where permitted by applicable law. Appropriate credit must be given.",
  "11. SCREENSHOTS AND VISUAL REPRODUCTION",
  "Visual captures may constitute restricted reproduction. Written permission from hr@ibcybersecurity.com is required before publishing or commercially using screenshots.",
  "PAGE D  /  COPYRIGHT LEGAL NOTICE",
  "12. COMMERCIAL USE",
  "Commercial use of protected original materials—including selling, paid products, advertising, or licensing—is strictly prohibited without prior written authorization.",
  "13. MODIFICATION AND DERIVATIVE USE",
  "Users must not modify, adapt, translate, redesign, rebrand, combine with other works, or create derivative works from the Company's protected original materials.",
  "14. DOWNLOADING AND DISTRIBUTION",
  "The availability of a file on the Website does not imply unrestricted redistribution rights. Downloaded materials must be used in accordance with their terms.",
  "15. PERMISSION AND AUTHORIZATION",
  "Written permission must be obtained from hr@ibcybersecurity.com before proposed use. Silence, delay, or failure to object does not constitute permission or consent.",
  "16. COPYRIGHT INFRINGEMENT REPORTING",
  "Suspected infringement may be reported to copyrightreport@ibcybersecurity.com with work details, infringing URL, ownership evidence, and accuracy confirmation.",
  "PAGE E  /  COPYRIGHT LEGAL NOTICE",
  "17. COPYRIGHT ENFORCEMENT AND REMEDIES",
  "The Company reserves all civil and legal remedies available under law against unauthorized reproduction or commercial exploitation.",
  "18. WEBSITE UNDER MAINTENANCE",
  "Website maintenance or content modification does not constitute abandonment or waiver of copyright in qualifying original works.",
  "19. NO TRANSFER OF COPYRIGHT",
  "Nothing on the Website transfers or licenses copyright ownership to any User unless made through a signed written instrument.",
  "20. NO IMPLIED LICENCE OR WAIVER",
  "No implied licence or waiver arises from publication of materials on the Website or failure to immediately object to unauthorized use.",
  "21. RESERVATION OF RIGHTS",
  "IB Cyber Security Private Limited reserves all rights in its original copyrighted materials under applicable law.",
  "PAGE F  /  COPYRIGHT LEGAL NOTICE",
  "22. GOVERNING LAW & 23. JURISDICTION",
  "Governed by Indian law (Copyright Act, 1957). Matters may be brought before competent courts in Bhubaneswar, Odisha, India, and the High Court of Orissa at Cuttack.",
  "23. OFFICIAL CONTACT INFORMATION",
  "IB Cyber Security Private Limited (Brand Name: IBCS)Emails: hr@ibcybersecurity.com | legaldepartment@ibcybersecurity.com | Phone:  | 8093424777",
  "24. LEGAL REFERENCES & 26. DOCUMENT CONTROL",
  "Prepared with reference to Sections 13, 14, 17, 51, 52, and 55 of the Copyright Act, 1957.Document ID: IBCS-COPYRIGHT-LEGAL-NOTICE-001 | Version: 1.0 | Effective: 26 September 2026.",
  "25. COPYRIGHT NOTICE & 28. LEGAL STATUS",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.Document ID is an internal control reference. Copyright protection arises automatically under applicable law.",
  "26. FINAL COPYRIGHT DECLARATION",
  "IB Cyber Security Private Limited hereby asserts and reserves all copyright and related intellectual-property rights in its original works made available through or in connection with the Website.END OF COPYRIGHT LEGAL NOTICE"
];