export const contentData = [
  "PAGE A  /  COPYRIGHT DECLARATION",
  "Copyright Declaration",
  "Formal declaration of our ownership and rights over original content and works.",
  "1. FORMAL COPYRIGHT DECLARATION",
  "IB Cyber Security Private Limited, a Private Limited Company operating under the public and brand name IBCS, hereby makes this formal Copyright Declaration in respect of qualifying original works and materials that it creates, develops, commissions, acquires, or lawfully controls.",
  "This Declaration applies to qualifying original works associated with https://ibcybersecurity.com, subject to applicable law, valid third-party rights, licences, and statutory limitations.",
  "2. DECLARANT AND COPYRIGHT OWNER",
  "Legal Name: IB Cyber Security Private Limited | Brand Name: IBCS | Type: Private Limited Company | Owner: IB Cyber Security Private Limited.",
  "The Company is the declared owner of copyright in original works where copyright is legally vested in the Company under the Copyright Act, 1957.",
  "3. WEBSITE COVERED BY THIS DECLARATION",
  "Applies to official Website https://ibcybersecurity.com containing original literary, artistic, audiovisual, software, and digital works.",
  "4. DECLARATION OF ORIGINAL WEBSITE CONTENT",
  "Claims copyright protection in original written content, articles, publications, informational content, cyber-awareness guides, reports, editorial materials, and content arrangements.",
  "Does not claim copyright over underlying facts, ideas, concepts, or short phrases that are not protected by copyright law.",
  "PAGE B  /  COPYRIGHT DECLARATION",
  "5. DECLARATION OF ORIGINAL CREATIVE WORKS",
  "Claims ownership over original UI/UX designs, visual layouts, graphic compositions, illustrations, graphical elements, icons, animations, motion graphics, and interactive visual elements.",
  "6. DECLARATION OF ORIGINAL DIGITAL MEDIA",
  "Claims ownership over original photographs, images, videos, audio materials, animations, digital publications, PDF documents, presentations, and educational resources.",
  "7. DECLARATION OF SOFTWARE AND SOURCE CODE",
  "Claims ownership over original source code, scripts, software implementations, website modules, programming expression, technical documentation, and database structures.",
  "Third-party libraries, open-source software, and external frameworks remain excluded from this declaration.",
  "8. DECLARATION OF BRANDING AND IDENTITY",
  "Claims ownership over Company-owned logos, brand graphics, visual identity materials, branding artwork, and digital branding assets.",
  "PAGE A  /  COPYRIGHT DECLARATION",
  "9. DECLARATION OF EDUCATIONAL & AWARENESS MATERIALS",
  "Claims ownership over cyber-awareness materials, educational publications, training resources, original guides, presentations, and digital learning assets.",
  "10. DECLARATION OF DOCUMENTS AND PUBLICATIONS",
  "Claims ownership over official publications, reports, notices, policies, manuals, PDF publications, digital documents, and templates.",
  "11. WEBSITE STRUCTURE AND COMPILATIONS",
  "Claims copyright in original compilations, selections, arrangements, and creative structures of content created by or lawfully controlled by the Company.",
  "12. THIRD-PARTY MATERIALS & RIGHTS",
  "Distinguishes original works from third-party materials (Google Fonts, open-source libraries/frameworks, licensed assets). Third-party assets remain subject to their respective owners' licence terms.",
  "13. LIMITATION OF THIS DECLARATION",
  "Does not claim ownership of third-party works, unprotectable facts/ideas, or statutory exceptions. Does not constitute a trademark, patent, or government certificate.",
  "PAGE B  /  COPYRIGHT DECLARATION",
  "14. BASIS OF COPYRIGHT OWNERSHIP",
  "Ownership arises through internal creation, employment, commissioning, valid assignment, contractual arrangements, or other legally recognized methods under law.",
  "15. RIGHTS RESERVED BY THE FOUNDATION",
  "Reserves rights of reproduction, publication, distribution, public communication, adaptation, translation, commercial exploitation, and licensing.",
  "16. NO AUTOMATIC TRANSFER OF RIGHTS",
  "Website access, viewing, URL sharing, linking, or downloading does not transfer copyright ownership. Specific permissions must be expressly granted in writing.",
  "17. EFFECT OF THIS DECLARATION & 18. WEBSITE MAINTENANCE",
  "Serves as a formal public ownership declaration under the Copyright Act, 1957. Temporary website maintenance, redesign, or asset revisions do not constitute abandonment of copyright.",
  "PAGE A  /  COPYRIGHT DECLARATION",
  "19. COPYRIGHT YEAR & 20. APPLICABLE INDIAN LAW",
  "Notice year (© 2026) indicates active publication. Governed principally by the Copyright Act, 1957 (Sections 13, 14, 17, 51, 52, 55).",
  "21. COPYRIGHT REGISTRATION & 22. RESERVATION OF RIGHTS",
  "Document ID (IBCS-COPYRIGHT-DECLARATION-001) is an internal control reference. The Company reserves all statutory rights and legal remedies against infringement.",
  "23. FORMAL COPYRIGHT SUMMARY",
  "Formally declares ownership/control over original works associated with the Website, subject to Indian copyright law, third-party rights, and statutory exceptions.",
  "24. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company)Website: https://ibcybersecurity.com | Email: hr@ibcybersecurity.com | Phone:  | 8093424777",
  "PAGE B  /  COPYRIGHT DECLARATION",
  "25. DOCUMENT CONTROL",
  "Document Title: Copyright Declaration | ID: IBCS-COPYRIGHT-DECLARATION-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.",
  "26. COPYRIGHT STATEMENT",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.IB Cyber Security Private Limited reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its original works.",
  "27. FINAL DECLARATION",
  "IB Cyber Security Private Limited hereby formally asserts its copyright ownership and lawful control over all qualifying original works associated with its official Website.END OF DECLARATION"
];
