export const contentData = [
  "PAGE A  /  COPYRIGHT OWNERSHIP STATEMENT",
  "Copyright Ownership Statement",
  "Clearly states who owns the copyright for our website, content and assets.",
  "1. FORMAL OWNERSHIP STATEMENT",
  "IB Cyber Security Private Limited, a legally registered Private Limited Company operating under the public and brand name IBCS, hereby formally declares that it is the copyright owner of qualifying original works and materials in which copyright is legally vested in the Company and which are created, developed, produced, or otherwise lawfully owned or controlled by the Company.",
  "This Copyright Ownership Statement applies to the qualifying original works and materials forming part of, incorporated into, or otherwise associated with the official Website of IB Cyber Security Private Limited available at https://ibcybersecurity.com.",
  "The Company asserts and reserves all copyright and related intellectual-property rights that it lawfully owns or controls in such original works, subject to the Copyright Act, 1957, other applicable laws of India, valid third-party rights, applicable licences, contractual arrangements and statutory limitations.",
  "2. IDENTIFICATION OF COPYRIGHT OWNER",
  "Legal Copyright Owner: IB Cyber Security Private LimitedPublic / Brand Name: IBCS | Organization Type: Private Limited Company | Official Website: https://ibcybersecurity.comFor the purposes of this Ownership Statement, references to the “Company” mean IB Cyber Security Private Limited.",
  "3. OWNERSHIP OF THE OFFICIAL WEBSITE",
  "IB Cyber Security Private Limited declares that the qualifying original materials forming part of or associated with its official Website are owned or lawfully controlled by the Company, subject to applicable law.",
  "The Company’s ownership claim extends, where legally protectable and lawfully owned or controlled by the Company, to the original written expression, creative elements, digital works, software and other copyrightable materials incorporated into or associated with the Website.",
  "4. OWNERSHIP OF ORIGINAL WRITTEN CONTENT",
  "The Company declares ownership of qualifying original written content created, developed or otherwise lawfully owned or controlled by the Company:• Original website content, paragraphs, articles, educational materials, reports, & guides• Original documentation, textual arrangements, and editorial expression",
  "Ownership applies to original expression and does not extend merely to facts, ideas, concepts, procedures, or methods.",
  "PAGE B  /  COPYRIGHT OWNERSHIP STATEMENT",
  "5. OWNERSHIP OF CONTENT & EXPRESSION",
  "Where the Company has created original expressive content, the Company claims copyright in the original expression, wording, arrangement and presentation of that content to the extent protected by applicable law.",
  "Includes original sentences, paragraphs, descriptions, explanations, written expressions, editorial presentation, content organization, selection, arrangement, and creative presentation.",
  "6. OWNERSHIP OF IMAGES & PHOTOGRAPHS",
  "Declares ownership or lawful control over original photographs, digital images, promotional graphics, awareness graphics, website imagery, visual compositions, and image-based creative works. No third-party image is claimed merely because it appears on the Website.",
  "7. OWNERSHIP OF AUDIO MATERIALS",
  "Declares ownership or lawful control over original audio recordings, voice recordings, narration, sound elements, audio presentations, educational audio, and other qualifying audio works.",
  "8. OWNERSHIP OF VIDEO MATERIALS & 9. ANIMATIONS",
  "Declares ownership or lawful control over original videos, educational videos, awareness videos, promotional videos, recorded presentations, video compositions, and animated visual compositions.",
  "PAGE A  /  COPYRIGHT OWNERSHIP STATEMENT",
  "10. GRAPHICS, INFOGRAPHICS & ILLUSTRATIONS",
  "Declares ownership or lawful control over original illustrations, graphic compositions, infographics, awareness graphics, diagrams, digital artwork, and visual compositions.",
  "11. SYMBOLS, ICONS AND VISUAL ELEMENTS",
  "Claims ownership over original icons, symbols, interface icons, graphical marks, visual indicators, decorative elements, and digital symbols specifically created or owned by the Company.",
  "12. LOGO AND BRANDING MATERIALS",
  "Declares ownership over Company-owned logo artwork, IBCS branding artwork, original brand graphics, visual identity elements, branding compositions, and digital branding assets.",
  "13. WATERMARKS & 14. UI/UX DESIGN",
  "Declares ownership over website watermarks, digital ownership markings, UI designs, page layouts, component arrangements, visual hierarchy, and interaction presentation.",
  "15. SOURCE CODE AND SOFTWARE",
  "Declares ownership over original source code, scripts, programming expression, software modules, website components, implementations, technical documentation, and code structures. Third-party libraries remain excluded.",
  "PAGE B  /  COPYRIGHT OWNERSHIP STATEMENT",
  "16. DATABASES AND COMPILATIONS",
  "Claims copyright protection in original compilations, selections, arrangements, and content structures created or lawfully controlled by the Company.",
  "17. PDFs AND DIGITAL DOCUMENTS",
  "Declares ownership over original PDF documents, digital publications, reports, guides, manuals, educational documents, awareness documents, and downloadable resources.",
  "18. EDUCATIONAL AND TRAINING MATERIALS",
  "Declares ownership over cyber-awareness materials, training materials, educational guides, awareness campaigns, educational presentations, learning resources, and instructional materials.",
  "19. DIGITAL ASSETS & 20. WEBSITE AS A WHOLE",
  "Declares ownership over digital graphics, illustrations, documents, media assets, website assets, promotional assets, educational assets, downloadable materials, and qualifying original components of the Website as a whole.",
  "PAGE A  /  COPYRIGHT OWNERSHIP STATEMENT",
  "21. BASIS OF OWNERSHIP & 22. THIRD-PARTY EXCLUSIONS",
  "Created through internal development. Expressly excludes Google Fonts, open-source libraries, open-source frameworks, third-party software components, licensed assets, third-party services, and embedded materials.",
  "23. NO CLAIM OVER NON-PROTECTABLE MATERIAL",
  "Does not claim copyright over facts, general ideas, concepts, methods, procedures, systems, processes, common information, generic elements, standard symbols, or standard interface elements.",
  "24. NO TRANSFER THROUGH WEBSITE ACCESS",
  "Viewing, URL sharing, linking, downloading, copy possession, or digital/source-code access does not transfer copyright ownership from the Company to any User.",
  "25. RESERVATION OF COPYRIGHT OWNERSHIP",
  "Expressly reserves all copyright and related rights. Online publication, viewing, downloading, sharing, or temporary display does not grant ownership to external parties.",
  "PAGE B  /  COPYRIGHT OWNERSHIP STATEMENT",
  "26. EFFECT OF OWNERSHIP STATEMENT & 27. REGISTRATION",
  "Serves as a formal public declaration under the Copyright Act, 1957. Document ID (IBCS-COPYRIGHT-OWNERSHIP-STATEMENT-001) is an internal document control reference.",
  "28. APPLICABLE LAW & 29. LEGAL RIGHTS RESERVED",
  "Made with reference to Copyright Act, 1957 (Sections 13, 14, 17, 18, 19, 51, 52, 55). Reserves all statutory rights and legal remedies against copyright infringement.",
  "30. WEBSITE MAINTENANCE & 31. OFFICIAL OWNER",
  "Maintenance, redesign, or migration does not constitute abandonment of copyright. Declared Copyright Owner: IB Cyber Security Private Limited (Public / Brand Name: IBCS).",
  "PAGE A  /  COPYRIGHT OWNERSHIP STATEMENT",
  "32. OFFICIAL ORGANIZATION INFORMATION",
  "IB Cyber Security Private Limited (Public / Brand Name: IBCS | Private Limited Company)",
  "Official Website: https://ibcybersecurity.com | Emails: hr@ibcybersecurity.com | legaldepartment@ibcybersecurity.com | Phone:  | 8093424777",
  "33. DOCUMENT CONTROL",
  "Document Title: Copyright Ownership Statement | ID: IBCS-COPYRIGHT-OWNERSHIP-STATEMENT-001 | Version: 1.0 | Effective & Last Updated: 26 September 2026.",
  "34. COPYRIGHT STATEMENT",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.IB Cyber Security Private Limited reserves all copyright and related intellectual-property rights that it lawfully owns or controls in its qualifying original works and materials.",
  "PAGE B  /  COPYRIGHT OWNERSHIP STATEMENT",
  "35. FINAL OWNERSHIP DECLARATION",
  "IB Cyber Security Private Limited hereby formally declares that it is the copyright owner of qualifying original works in which copyright is legally vested in the Company.",
  "This declaration includes original written expression, content, sentences, paragraphs, articles, images, photographs, audio, videos, animations, graphics, illustrations, symbols, icons, watermarks, branding materials, UI/UX creative expression, visual designs, source code, software, documents, educational materials, digital assets, compilations, selections, and arrangements.",
  "Third-party materials remain excluded from this ownership declaration.",
  "All rights reserved subject to the Copyright Act, 1957, other applicable laws of India, valid third-party rights, applicable licences, statutory exceptions, and limitations.",
  "© 2026 IB Cyber Security Private Limited. All Rights Reserved.END OF COPYRIGHT OWNERSHIP STATEMENT"
];
